#!/usr/bin/env python3
"""
Insert CS & IT master's programs from Mastersportal pages 1-5 into Supabase.
Uses REST API with upsert-by-fingerprint to be idempotent.
"""
import os, sys, hashlib, httpx
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
from dotenv import load_dotenv

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", ".env.local"))

SB_URL = os.environ["NEXT_PUBLIC_SUPABASE_URL"]
SB_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
HEADERS = {
    "apikey": SB_KEY,
    "Authorization": f"Bearer {SB_KEY}",
    "Content-Type": "application/json",
    "Prefer": "resolution=ignore-duplicates,return=minimal",
}

SOURCE_URL = "https://www.mastersportal.eu/disciplines/34/computer-science-it.html"

def fp(program_name: str, country: str) -> str:
    raw = f"{program_name.lower().strip()}|{country.lower()}|master"
    return hashlib.sha256(raw.encode()).hexdigest()


PROGRAMS = [
    # PAGE 1
    dict(university="Vita-Salute San Raffaele University", program_name="Health Informatics", country="Italy", city="Milano", duration_years=2.0, tuition_usd_year=6640, scholarship_available=False, description="MSc developing advanced informatics skills applied to medicine, preparing professionals for digital healthcare and medical AI roles.", field_of_study=["Health Informatics","Medical Data","Artificial Intelligence"]),
    dict(university="Marbella Design Academy", program_name="Innovative Design", country="Spain", city="Málaga", duration_years=0.9, tuition_usd_year=18000, scholarship_available=False, description="Awarded as an official UK Master's degree by University of Bedfordshire; studio-based programme on innovative design methods and technology.", field_of_study=["Design","Innovation","Technology"]),
    dict(university="KU Leuven", program_name="Information Management", country="Belgium", city="Leuven", duration_years=1.0, tuition_usd_year=1181, scholarship_available=False, description="Non-technical MSc emphasising efficient application and management of information technology in business contexts including finance, HR, and logistics.", field_of_study=["Information Management","Business IT","Data Management"]),
    dict(university="Webster Geneva Campus", program_name="Business Administration with an Emphasis in Cybersecurity", country="Switzerland", city="Geneva", duration_years=1.0, tuition_usd_year=38426, scholarship_available=False, description="MBA with cybersecurity emphasis teaching business competencies needed to develop and implement value-creating solutions while managing digital risk.", field_of_study=["Cybersecurity","Business Administration","Management"]),
    dict(university="Radboud University", program_name="Language and Communication Technologies", country="Netherlands", city="Nijmegen", duration_years=1.0, tuition_usd_year=2694, scholarship_available=False, description="MSc focusing on improving linguistic and communicative properties of automatic language systems; ideal for students interested in NLP and AI.", field_of_study=["Computational Linguistics","NLP","Language Technology"]),
    dict(university="EAE Business School Barcelona Campus", program_name="Business Administration and AI Track", country="Spain", city="Barcelona", duration_years=0.8, tuition_usd_year=None, scholarship_available=False, description="MBA programme designed to accelerate professionals and entrepreneurs combining core business competencies with artificial intelligence applications.", field_of_study=["Business Administration","Artificial Intelligence","Management"]),
    dict(university="Vrije Universiteit Brussel (VUB)", program_name="Computer Science", country="Belgium", city="Brussels", duration_years=2.0, tuition_usd_year=1182, scholarship_available=False, description="Two-year MSc providing deep scientific understanding of computer science with specialised elective courses for academic bachelor holders.", field_of_study=["Computer Science","Software Engineering","Algorithms"]),
    dict(university="emlyon business school", program_name="Healthcare Innovation and Data Science", country="France", city="Lyon", duration_years=2.0, tuition_usd_year=19250, scholarship_available=False, description="MSc meeting growing demand for digital transformation in healthcare, combining innovation management with advanced data science, analytics, and AI skills.", field_of_study=["Healthcare IT","Data Science","Innovation Management"]),
    dict(university="Howest University of Applied Sciences", program_name="Advanced Bachelor of Bioinformatics", country="Belgium", city="Brugge", duration_years=1.0, tuition_usd_year=1200, scholarship_available=False, description="One-year post-bachelor programme preparing graduates to operate at the intersection of life sciences and IT in one of the fastest-growing fields.", field_of_study=["Bioinformatics","Life Sciences","Data Science"]),
    dict(university="JUNIA - Graduate School of Science and Engineering", program_name="Big Data", country="France", city="Lille", duration_years=2.0, tuition_usd_year=9770, scholarship_available=False, description="MSc developing cutting-edge skills in AI and Big Data through advanced machine learning, NLP, computer vision, and cloud architecture.", field_of_study=["Big Data","Artificial Intelligence","Machine Learning"]),
    dict(university="Vrije Universiteit Brussel (VUB)", program_name="Applied Computer Science", country="Belgium", city="Brussels", duration_years=2.0, tuition_usd_year=1182, scholarship_available=False, description="MSc developing computer and data science skills through specialised courses for students seeking practical computing expertise with academic depth.", field_of_study=["Computer Science","Data Science","Software Development"]),
    dict(university="SupBiotech Paris", program_name="Biotechnology and AI", country="France", city="Paris", duration_years=2.0, tuition_usd_year=13950, scholarship_available=False, description="Cutting-edge programme by SupBiotech Paris in partnership with EPITA and ESME, training future bioinformatics and AI experts.", field_of_study=["Bioinformatics","Artificial Intelligence","Biotechnology"]),
    dict(university="NOVA IMS", program_name="Data Science for Marketing", country="Portugal", city="Lisbon", duration_years=2.0, tuition_usd_year=3000, scholarship_available=False, description="MSc filling a gap in postgraduate training for marketing professionals needing analytical skills for data-driven marketing model development.", field_of_study=["Data Science","Marketing Analytics","Machine Learning"]),
    dict(university="Fresenius University of Applied Sciences", program_name="SAP Engineering and Analytics", country="Germany", city="Heidelberg", duration_years=2.0, tuition_usd_year=10560, scholarship_available=False, description="MSc empowering students to gain understanding of digital transformation, software engineering, and advanced data science with SAP technologies.", field_of_study=["SAP","Data Analytics","Digital Transformation"]),
    dict(university="Webster University Athens", program_name="Business Administration with an Emphasis in Cybersecurity", country="Greece", city="Athens", duration_years=2.0, tuition_usd_year=12480, scholarship_available=False, description="Flexible MBA with cybersecurity specialisation offering small classes, personal attention, and a real-world approach to digital business security.", field_of_study=["Cybersecurity","Business Administration","Risk Management"]),
    dict(university="Vrije Universiteit Brussel (VUB)", program_name="Geography", country="Belgium", city="Brussels", duration_years=2.0, tuition_usd_year=1182, scholarship_available=False, description="MSc providing hands-on training in qualitative and quantitative geographical research with specialisation in Earth, Climate, and Geo-information Sciences.", field_of_study=["Geography","GIS","Climate Science"]),
    dict(university="Utrecht University", program_name="Economics and Data Analysis", country="Netherlands", city="Utrecht", duration_years=1.0, tuition_usd_year=2694, scholarship_available=False, description="MSc providing solid theoretical foundation in microeconomics, macroeconomics, and econometrics for applied quantitative data analysis careers.", field_of_study=["Economics","Data Analysis","Econometrics"]),
    dict(university="EU Business School", program_name="Digital Business", country="Spain", city="Barcelona", duration_years=1.0, tuition_usd_year=16350, scholarship_available=False, description="MSc exploring the theoretical and practical foundations, implementation and business models that make up the digital business landscape.", field_of_study=["Digital Business","E-commerce","Business Strategy"]),
    dict(university="Utrecht University", program_name="Business Informatics", country="Netherlands", city="Utrecht", duration_years=2.0, tuition_usd_year=2694, scholarship_available=False, description="MSc focusing on design and use of information and computing science theories applied in business and organisational domains with a holistic approach.", field_of_study=["Business IT","Information Systems","Data Management"]),
    dict(university="JUNIA - Graduate School of Science and Engineering", program_name="Software Engineering and Information Systems", country="France", city="Lille", duration_years=2.0, tuition_usd_year=9770, scholarship_available=False, description="MSc building strong skills in software engineering through web and mobile development, Java applications, object-oriented design, and quality-driven coding.", field_of_study=["Software Engineering","Information Systems","Web Development"]),
    # PAGE 2
    dict(university="Utrecht University", program_name="Data Science", country="Netherlands", city="Utrecht", duration_years=2.0, tuition_usd_year=2694, scholarship_available=False, description="MSc teaching the principles and core fundamentals of data science including theories, tools, techniques, and methodologies for data-driven problem solving.", field_of_study=["Data Science","Machine Learning","Statistics"]),
    dict(university="Aeres University of Applied Sciences", program_name="Agribusiness Development", country="Netherlands", city="Dronten", duration_years=1.0, tuition_usd_year=2695, scholarship_available=False, description="MSc preparing professionals for careers in international agribusiness companies focused on sustainable food production and supply chain management.", field_of_study=["Agribusiness","Food Systems","Data Analytics"]),
    dict(university="University of Padua", program_name="ICT for Internet and Multimedia", country="Italy", city="Padova", duration_years=2.0, tuition_usd_year=2739, scholarship_available=False, description="MSc capturing the evolution of information engineering with a modern approach combining solid fundamental knowledge and advanced technological skills.", field_of_study=["ICT","Multimedia","Internet Engineering"]),
    dict(university="Pompeu Fabra University", program_name="EMAI - Erasmus Mundus Joint Master in Artificial Intelligence", country="Spain", city="Barcelona", duration_years=2.0, tuition_usd_year=9000, scholarship_available=True, description="Two-year Erasmus Mundus joint MSc funded by the European Commission providing comprehensive theory and practice in AI; full scholarships available.", field_of_study=["Artificial Intelligence","Machine Learning","Cognitive Science"]),
    dict(university="EU Business School", program_name="Business Analytics and Data Science", country="Online", city="Online", duration_years=1.0, tuition_usd_year=16350, scholarship_available=False, description="Online MSc giving students a foundation in data science using industry-leading software, tools, and applications for data-driven business decisions.", field_of_study=["Business Analytics","Data Science","Machine Learning"]),
    dict(university="EADA Business School", program_name="Artificial Intelligence for Business", country="Spain", city="Barcelona", duration_years=0.75, tuition_usd_year=None, scholarship_available=False, description="Nine-month MSc equipping students to lead in the data-driven future, combining AI technical skills with strategic leadership to optimise business operations.", field_of_study=["Artificial Intelligence","Business Strategy","Data Science"]),
    dict(university="Hasselt University", program_name="Statistics and Data Science", country="Belgium", city="Hasselt", duration_years=2.0, tuition_usd_year=2699, scholarship_available=False, description="Two-year MSc combining solid study of statistical principles and modern data science with a focus on life sciences applications including clinical trials and genomics.", field_of_study=["Statistics","Data Science","Bioinformatics"]),
    dict(university="SBS Swiss Business School Barcelona", program_name="Business Analytics", country="Spain", city="Barcelona", duration_years=1.0, tuition_usd_year=17575, scholarship_available=False, description="MSc developing skills to understand business data and turn it into actionable insights, staying ahead of the curve in today's data-driven business world.", field_of_study=["Business Analytics","Data Science","Strategy"]),
    dict(university="EU Business School", program_name="Artificial Intelligence for Business", country="Germany", city="Munich", duration_years=1.0, tuition_usd_year=16350, scholarship_available=False, description="MSc providing the opportunity to explore AI technology in depth across a range of business contexts at the Munich campus.", field_of_study=["Artificial Intelligence","Business Strategy","Technology Management"]),
    dict(university="USTP - University of Applied Sciences St. Pölten", program_name="Digital Innovation and Research", country="Austria", city="Sankt Pölten", duration_years=2.0, tuition_usd_year=726, scholarship_available=False, description="MSc bridging applied research, innovation, and digitalisation for professionals passionate about leading digital transformation strategies.", field_of_study=["Digital Innovation","Research Methods","Digitalization"]),
    dict(university="EU Business School", program_name="Business Analytics and Data Science", country="Spain", city="Barcelona", duration_years=1.0, tuition_usd_year=16350, scholarship_available=False, description="MSc giving students a comprehensive foundation in data science using industry-leading software, tools, and applications for the Barcelona campus.", field_of_study=["Business Analytics","Data Science","Machine Learning"]),
    dict(university="Universidade Nova de Lisboa - NOVA School of Law", program_name="Law Applied to Technology (Law and Tech)", country="Portugal", city="Lisbon", duration_years=2.0, tuition_usd_year=3600, scholarship_available=False, description="MSc focusing on digital and other emerging technological transformations, studying law in an international and comparative way.", field_of_study=["Technology Law","Digital Law","Cybersecurity Policy"]),
    dict(university="Utrecht University", program_name="Geographical Information Management and Applications (GIMA)", country="Netherlands", city="Utrecht", duration_years=2.0, tuition_usd_year=2694, scholarship_available=False, description="Two-year joint MSc in geo-information available in part-time and full-time modes, delivered with multiple Dutch universities.", field_of_study=["GIS","Geoinformatics","Spatial Data"]),
    dict(university="EU Business School", program_name="Business Analytics and Data Science", country="Germany", city="Munich", duration_years=1.0, tuition_usd_year=16350, scholarship_available=False, description="Hands-on MSc giving students a comprehensive foundation in data science using industry-leading software and applications at the Munich campus.", field_of_study=["Business Analytics","Data Science","Machine Learning"]),
    dict(university="Utrecht University", program_name="Human Computer Interaction", country="Netherlands", city="Utrecht", duration_years=2.0, tuition_usd_year=2694, scholarship_available=False, description="MSc exploring how computing devices can be adapted to individual users and how to develop new approaches to human-machine interaction.", field_of_study=["HCI","UX Design","Cognitive Science"]),
    dict(university="University College Dublin", program_name="Human Computer Interaction", country="Ireland", city="Dublin", duration_years=1.0, tuition_usd_year=9515, scholarship_available=False, description="MSc combining core HCI elements from a social science perspective, harnessing expertise in the School of Information and Communication Studies.", field_of_study=["HCI","UX","Information Studies"]),
    dict(university="Vlerick Business School", program_name="Business Analytics and AI", country="Belgium", city="Gent", duration_years=0.8, tuition_usd_year=None, scholarship_available=False, description="Ten-month MSc combining analytical and strategic foundations to translate data and AI into real business value with leadership skills.", field_of_study=["Business Analytics","Artificial Intelligence","Data Strategy"]),
    dict(university="Global Banking School Malta", program_name="Master of Science in Information Technology Management", country="Malta", city="San Gwann", duration_years=1.0, tuition_usd_year=10000, scholarship_available=False, description="MSc addressing growth in the IT industry, focusing on technology infrastructure from IT service desk support to data-driven executive decision-making.", field_of_study=["IT Management","Cybersecurity","Data Analytics"]),
    dict(university="Vrije Universiteit Brussel (VUB)", program_name="Applied Informatics - Artificial Intelligence and Data Science", country="Belgium", city="Brussels", duration_years=1.0, tuition_usd_year=1182, scholarship_available=False, description="MSc enabling students to master practical aspects of informatics, preparing for jobs in software development, data processing, and system analysis.", field_of_study=["Artificial Intelligence","Data Science","Software Development"]),
    dict(university="NEOMA Business School", program_name="Artificial Intelligence for Business", country="France", city="Rouen", duration_years=1.25, tuition_usd_year=15600, scholarship_available=False, description="MSc training professionals to create, manage, and implement AI solutions within organisations for competitive advantage.", field_of_study=["Artificial Intelligence","Business Strategy","Digital Transformation"]),
    # PAGE 3
    dict(university="EAE Business School Barcelona Campus", program_name="Big Data and Analytics", country="Spain", city="Barcelona", duration_years=0.8, tuition_usd_year=None, scholarship_available=False, description="MSc offering complete training for professionals in big data and analytics, covering the most in-demand market skills.", field_of_study=["Big Data","Analytics","Business Intelligence"]),
    dict(university="University College Dublin", program_name="Information Systems", country="Ireland", city="Dublin", duration_years=1.0, tuition_usd_year=9515, scholarship_available=False, description="MSc incorporating information technology and data analytics with a grounding in social science for well-rounded IS professionals.", field_of_study=["Information Systems","IT Management","Business Analytics"]),
    dict(university="University College Dublin", program_name="Library and Information Studies", country="Ireland", city="Dublin", duration_years=1.0, tuition_usd_year=9515, scholarship_available=False, description="MSc preparing graduates for professional settings including academic, public, and special libraries as well as information-based roles.", field_of_study=["Library Science","Information Management","Digital Libraries"]),
    dict(university="SDA Bocconi School of Management", program_name="Master in Sustainability Management", country="Italy", city="Milan", duration_years=1.0, tuition_usd_year=30000, scholarship_available=False, description="MSc from SDA Bocconi addressing sustainability, climate change, biodiversity, and energy challenges for governments, companies, and civil society.", field_of_study=["Sustainability","ESG","Data Analytics"]),
    dict(university="EAE Business School Barcelona Campus", program_name="International Business STEM", country="Spain", city="Barcelona", duration_years=0.8, tuition_usd_year=None, scholarship_available=False, description="MSc preparing professionals to navigate global markets and lead enterprises in an interconnected, tech-driven world.", field_of_study=["International Business","Technology","STEM"]),
    dict(university="USTP - University of Applied Sciences St. Pölten", program_name="Cyber Security and Resilience", country="Austria", city="Sankt Pölten", duration_years=2.0, tuition_usd_year=726, scholarship_available=False, description="Two-year MSc teaching how to build and run resilient information systems, covering secure architecture, risk management, and cyber defence.", field_of_study=["Cybersecurity","Resilience Engineering","Information Security"]),
    dict(university="NEOMA Business School", program_name="Business Analytics", country="France", city="Rouen", duration_years=1.25, tuition_usd_year=15600, scholarship_available=False, description="MSc equipping students with skills and knowledge to transform complex data into actionable insights for strategic decision-making.", field_of_study=["Business Analytics","Data Science","Strategic Decision Making"]),
    dict(university="USTP - University of Applied Sciences St. Pölten", program_name="Joint Master in Applied XR - Gamified Reality Applications for Real-world Challenges and Experiences (GRACE)", country="Austria", city="Sankt Pölten", duration_years=2.0, tuition_usd_year=726, scholarship_available=False, description="Joint MSc in Applied XR featuring real-world projects guided by an international mentor network, turning innovation into impact.", field_of_study=["Extended Reality","XR","Game Design","Innovation"]),
    dict(university="ESIEE Paris - Université Gustave Eiffel", program_name="Management of Technology - Information Systems", country="France", city="Paris", duration_years=1.5, tuition_usd_year=7000, scholarship_available=False, description="MSc taught entirely in English equipping students to become international project managers working at the interface of management and technology.", field_of_study=["IT Management","Information Systems","Project Management"]),
    dict(university="ESSCA School of Management", program_name="Business Analytics", country="France", city="Boulogne-Billancourt", duration_years=1.0, tuition_usd_year=21800, scholarship_available=False, description="MSc combining the power of data, finance, and artificial intelligence into a single future-oriented programme for analytical business leaders.", field_of_study=["Business Analytics","Finance","Artificial Intelligence"]),
    dict(university="Utrecht University", program_name="Computing Science", country="Netherlands", city="Utrecht", duration_years=2.0, tuition_usd_year=2694, scholarship_available=False, description="MSc allowing students to dive into the depths of fundamental computing science, exploring theoretical and applied aspects of the discipline.", field_of_study=["Computer Science","Theory","Algorithms"]),
    dict(university="Free University of Bozen-Bolzano", program_name="Software Engineering", country="Italy", city="Bolzano", duration_years=2.0, tuition_usd_year=1200, scholarship_available=False, description="MSc leveraging next-generation technologies including Cloud Computing, IoT, and Analytics to create and engineer innovative information systems.", field_of_study=["Software Engineering","Cloud Computing","IoT"]),
    dict(university="University of Padua", program_name="Complex and Data Driven Chemistry", country="Italy", city="Padova", duration_years=2.0, tuition_usd_year=2739, scholarship_available=False, description="MSc introducing fundamental concepts of data-driven chemistry including statistical learning, chemometrics, and design of experiments.", field_of_study=["Computational Chemistry","Data Science","Chemometrics"]),
    dict(university="Free University of Bozen-Bolzano", program_name="Computing for Data Science", country="Italy", city="Bolzano", duration_years=2.0, tuition_usd_year=1200, scholarship_available=False, description="MSc providing key competencies to develop next-generation information systems for data management, fact discovery, prediction, and decision support.", field_of_study=["Data Science","Information Systems","Machine Learning"]),
    dict(university="Free University of Bozen-Bolzano", program_name="Data Analytics for Economics and Management", country="Italy", city="Bolzano", duration_years=2.0, tuition_usd_year=1200, scholarship_available=False, description="MSc designed for students developing skills in computing, econometrics, statistics, and mathematics for economic data analysis problems.", field_of_study=["Data Analytics","Economics","Management Science"]),
    dict(university="LUMSA University", program_name="Financial Data Analytics and Sustainable Finance (FINDATA)", country="Italy", city="Rome", duration_years=1.0, tuition_usd_year=6000, scholarship_available=False, description="Joint MSc organised by four European universities: University of Pardubice, European University Cyprus, LUMSA, and Vilnius University.", field_of_study=["Financial Analytics","Sustainable Finance","Data Science"]),
    dict(university="LUMSA University", program_name="Management, Finance and Data Analytics", country="Italy", city="Rome", duration_years=2.0, tuition_usd_year=4390, scholarship_available=False, description="MSc training graduates with skills in management, finance, and data analysis to operate as managers, consultants, and analysts.", field_of_study=["Management","Finance","Data Analytics"]),
    dict(university="LUMSA University", program_name="AI for Marketing and Communication", country="Italy", city="Rome", duration_years=2.0, tuition_usd_year=4390, scholarship_available=False, description="MSc providing comprehensive study of marketing and communication theory combined with practical AI tools for traditional and digital media.", field_of_study=["Artificial Intelligence","Marketing","Digital Communication"]),
    dict(university="Universidad Europea", program_name="Business Analytics and Business Intelligence", country="Spain", city="Madrid", duration_years=0.75, tuition_usd_year=None, scholarship_available=False, description="Nine-month MSc focusing on collecting, structuring, and analysing company data to optimise decision-making with BI tools.", field_of_study=["Business Analytics","Business Intelligence","Data Management"]),
    # PAGE 4
    dict(university="Constructor University", program_name="Data Science for Society and Business", country="Germany", city="Bremen", duration_years=2.0, tuition_usd_year=20000, scholarship_available=False, description="Highly selective two-year MSc for business and social science students aiming to become data science experts in applied organisational contexts.", field_of_study=["Data Science","Social Science","Business Analytics"]),
    dict(university="Radboud University", program_name="Cyber Security", country="Netherlands", city="Nijmegen", duration_years=2.0, tuition_usd_year=2695, scholarship_available=False, description="MSc teaching how to assess the security of existing ICT systems and develop more secure future solutions as reliance on IT increases.", field_of_study=["Cybersecurity","Security Analysis","Cryptography"]),
    dict(university="Roskilde University", program_name="Computer Science", country="Denmark", city="Roskilde", duration_years=2.0, tuition_usd_year=None, scholarship_available=False, description="Practice-oriented MSc focusing on developing complex, reliable, user-friendly, and long-lasting IT systems; tuition-free for EU/EEA students.", field_of_study=["Computer Science","Software Development","System Design"]),
    dict(university="Turiba University", program_name="Information Technology", country="Latvia", city="Riga", duration_years=1.5, tuition_usd_year=3090, scholarship_available=False, description="MSc providing comprehensive knowledge of the global IT world and its development, fostering professional growth in technology management.", field_of_study=["Information Technology","IT Management","Networking"]),
    dict(university="Masaryk University", program_name="Artificial Intelligence and Data Processing", country="Czech Republic", city="Brno", duration_years=2.0, tuition_usd_year=4500, scholarship_available=False, description="MSc preparing students for design and development of intelligent systems and big data analysis in this rapidly developing field.", field_of_study=["Artificial Intelligence","Data Processing","Machine Learning"]),
    dict(university="Reykjavík University", program_name="Digital Management and Data Analysis", country="Iceland", city="Reykjavík", duration_years=1.0, tuition_usd_year=11067, scholarship_available=False, description="MSc equipping graduates with cutting-edge interdisciplinary expertise in digital management and data analysis that is highly sought after across industries.", field_of_study=["Digital Management","Data Analysis","Innovation"]),
    dict(university="Wageningen University and Research", program_name="Data Science for Food and Health", country="Netherlands", city="Wageningen", duration_years=2.0, tuition_usd_year=2694, scholarship_available=False, description="MSc integrating data science with food and health domains, using data-driven approaches to solve complex questions in nutrition and food systems.", field_of_study=["Data Science","Food Science","Health Analytics"]),
    dict(university="LUT University", program_name="Software Product Management and Business", country="Finland", city="Lahti", duration_years=2.0, tuition_usd_year=None, scholarship_available=False, description="MSc focusing on design, implementation, and maintenance of software and digital services in their business context; tuition-free for EU students.", field_of_study=["Software Management","Product Development","Business"]),
    dict(university="Technological University of the Shannon", program_name="Software Engineering", country="Ireland", city="Athlone", duration_years=1.0, tuition_usd_year=5880, scholarship_available=False, description="MSc enhancing knowledge and expertise in active research and development areas of software engineering for computer professionals.", field_of_study=["Software Engineering","Research","Software Quality"]),
    dict(university="Lancaster University Leipzig", program_name="Data Science", country="Germany", city="Leipzig", duration_years=1.0, tuition_usd_year=16600, scholarship_available=False, description="MSc ensuring advanced skills, knowledge, and experience in this rapidly expanding, highly in-demand field to achieve career aspirations.", field_of_study=["Data Science","Machine Learning","Analytics"]),
    dict(university="HTW Berlin", program_name="Project Management and Data Science", country="Germany", city="Berlin", duration_years=2.0, tuition_usd_year=8800, scholarship_available=False, description="International MSc preparing students with academic knowledge, real-world experience, and industry connections for managing data-driven projects.", field_of_study=["Project Management","Data Science","International Business"]),
    dict(university="GBSB Global Business School", program_name="Blockchain Management", country="Malta", city="Birkirkara", duration_years=1.0, tuition_usd_year=7750, scholarship_available=False, description="MSc providing deep understanding of blockchain from its origins in cryptocurrency to its broader applications in securing digital transactions.", field_of_study=["Blockchain","Cryptocurrency","Digital Finance"]),
    dict(university="Radboud University", program_name="Software Science", country="Netherlands", city="Nijmegen", duration_years=2.0, tuition_usd_year=2695, scholarship_available=False, description="MSc specialisation focusing on analysing and testing code in order to both improve and simplify it for more reliable software systems.", field_of_study=["Software Engineering","Code Analysis","Formal Methods"]),
    dict(university="University College Cork", program_name="Mathematical Modelling and Machine Learning", country="Ireland", city="Cork", duration_years=1.0, tuition_usd_year=8000, scholarship_available=False, description="MSc providing training in the use and development of modern numerical methods and machine-learning software for applied research.", field_of_study=["Machine Learning","Mathematical Modelling","Numerical Methods"]),
    dict(university="Wageningen University and Research", program_name="Geographical Information Management and Applications", country="Netherlands", city="Wageningen", duration_years=2.0, tuition_usd_year=2694, scholarship_available=False, description="Joint MSc delivered by Wageningen, TU Delft, Utrecht University, and University of Twente — geo-information experts from four universities.", field_of_study=["GIS","Geoinformatics","Spatial Data Science"]),
    dict(university="Tomorrow University of Applied Sciences", program_name="Impact MSc in Data Leadership in Sustainable Innovation", country="Germany", city="Online", duration_years=1.5, tuition_usd_year=None, scholarship_available=False, description="MSc equipping students to manage data-driven sustainability projects, craft impactful strategies, and lead sustainability initiatives with technology.", field_of_study=["Data Leadership","Sustainability","Digital Innovation"]),
    dict(university="Fresenius University of Applied Sciences", program_name="Computer Science", country="Germany", city="Berlin", duration_years=2.0, tuition_usd_year=10560, scholarship_available=False, description="MSc for digital experts deepening methodological and technological knowledge in Cyber Security and Artificial Intelligence through German study.", field_of_study=["Computer Science","Cybersecurity","Artificial Intelligence"]),
    dict(university="University of Vaasa", program_name="Industrial Systems Analytics", country="Finland", city="Vaasa", duration_years=2.0, tuition_usd_year=None, scholarship_available=False, description="MSc preparing future leaders in energy and technology sectors by combining engineering expertise with practical business and operational excellence.", field_of_study=["Systems Analytics","Energy Technology","Industrial Engineering"]),
    dict(university="Jönköping University", program_name="Cybersecurity (one year)", country="Sweden", city="Jönköping", duration_years=1.0, tuition_usd_year=None, scholarship_available=False, description="One-year MSc designed to complement a Bachelor's degree with the latest cybersecurity advances for digitalization projects across industries.", field_of_study=["Cybersecurity","Risk Management","Digital Forensics"]),
    dict(university="Technological University of the Shannon", program_name="Data Analytics (Athlone)", country="Ireland", city="Athlone", duration_years=1.0, tuition_usd_year=7000, scholarship_available=False, description="Industry-focused MSc equipping graduates with skills and aptitudes necessary to excel in the emerging field of Big Data and Data Analytics.", field_of_study=["Data Analytics","Big Data","Business Intelligence"]),
    # PAGE 5
    dict(university="Università Cattolica del Sacro Cuore", program_name="Data Analytics for Business", country="Italy", city="Milan", duration_years=2.0, tuition_usd_year=6850, scholarship_available=False, description="MSc offered jointly with the Faculty of Mathematics, Physics and Natural Sciences combining quantitative analysis with business applications.", field_of_study=["Data Analytics","Business","Statistics"]),
    dict(university="Northumbria University", program_name="Computing and Technology", country="Netherlands", city="Amsterdam", duration_years=1.0, tuition_usd_year=24891, scholarship_available=False, description="MSc designed to update, extend and deepen knowledge in computing, IT, and wider digital leadership subjects to enhance career opportunities.", field_of_study=["Computing","IT Management","Digital Leadership"]),
    dict(university="University of Pécs", program_name="Computer Science Engineering", country="Hungary", city="Pécs", duration_years=2.0, tuition_usd_year=6891, scholarship_available=False, description="MSc providing engineers from technical IT disciplines with skills to pursue a career in computer and information engineering.", field_of_study=["Computer Science","Engineering","Information Technology"]),
    dict(university="ESCP Business School", program_name="Strategy and Digital Business", country="France", city="Paris", duration_years=2.0, tuition_usd_year=None, scholarship_available=False, description="Rigorous two-year programme equipping students with strategic, digital, and entrepreneurial skills demanded by today's job markets.", field_of_study=["Digital Strategy","Business Management","Innovation"]),
    dict(university="Masaryk University", program_name="Computer Systems, Communication and Security", country="Czech Republic", city="Brno", duration_years=2.0, tuition_usd_year=4500, scholarship_available=False, description="MSc leading graduates to understanding of architectures, principles, and design methods for secure computer systems including network communications.", field_of_study=["Systems Security","Networking","Computer Architecture"]),
    dict(university="Radboud University", program_name="Artificial Intelligence - Human Centered Intelligent Systems", country="Netherlands", city="Nijmegen", duration_years=2.0, tuition_usd_year=2695, scholarship_available=False, description="Interdisciplinary MSc specialisation studying and developing intelligent systems from medical AI to artificial agents and human-machine interfaces.", field_of_study=["Artificial Intelligence","HCI","Medical AI"]),
    dict(university="Kaunas University of Technology", program_name="Artificial Intelligence in Computer Science", country="Lithuania", city="Kaunas", duration_years=2.0, tuition_usd_year=5538, scholarship_available=False, description="MSc convening competences for students to actively contribute to improvement and innovation in the rapidly developing field of AI and informatics.", field_of_study=["Artificial Intelligence","Computer Science","Machine Learning"]),
    dict(university="Radboud University", program_name="Cyber Security and AI", country="Netherlands", city="Nijmegen", duration_years=2.0, tuition_usd_year=2695, scholarship_available=False, description="Unique MSc programme exploring the interplay between AI and Cyber Security, covering the latest approaches and challenges of both domains.", field_of_study=["Cybersecurity","Artificial Intelligence","Security Engineering"]),
    dict(university="University College Cork", program_name="Cybersecurity", country="Ireland", city="Cork", duration_years=1.0, tuition_usd_year=8000, scholarship_available=False, description="MSc providing in-depth understanding of practical and theoretical aspects of cybersecurity for securing digital systems that operate 24x7.", field_of_study=["Cybersecurity","Security Engineering","Digital Forensics"]),
    dict(university="Warsaw University of Technology", program_name="Mobile Mapping and Navigation Systems", country="Poland", city="Warsaw", duration_years=1.5, tuition_usd_year=3600, scholarship_available=False, description="MSc in Geodesy and Cartography specialisation on collecting, processing, and analysing spatial data for modern navigation systems.", field_of_study=["Geomatics","Navigation","Spatial Data"]),
    dict(university="Atlantic Technological University", program_name="Computing", country="Ireland", city="Galway", duration_years=1.0, tuition_usd_year=6300, scholarship_available=False, description="MSc enabling graduates and professionals to develop advanced thinking and technical know-how in a range of technology-centric disciplines.", field_of_study=["Computing","Software Development","Technology Management"]),
    dict(university="GBSB Global Business School", program_name="Enterprise Cybersecurity Management", country="Spain", city="Madrid", duration_years=0.75, tuition_usd_year=None, scholarship_available=False, description="Nine-month MSc preparing graduates to transform governance into action through enterprise cybersecurity management and strategic security leadership.", field_of_study=["Cybersecurity","Enterprise Security","Governance"]),
    dict(university="Écoles d'Ingénieurs - Engineering School (ECE)", program_name="Data and AI", country="France", city="Bordeaux", duration_years=2.0, tuition_usd_year=10950, scholarship_available=False, description="MSc mastering Machine Learning algorithms and data analysis tools including R, Spark, Python, and Matlab with focus on real-world AI applications.", field_of_study=["Data Science","Artificial Intelligence","Machine Learning"]),
    dict(university="Jönköping University", program_name="Software Engineering for AI", country="Sweden", city="Jönköping", duration_years=2.0, tuition_usd_year=None, scholarship_available=False, description="Two-year MSc from an international university known for student entrepreneurship, strong research, and successful industry collaborations in AI engineering.", field_of_study=["Software Engineering","Artificial Intelligence","System Design"]),
    dict(university="IÉSEG School of Management", program_name="Business Analysis and Consulting", country="France", city="Paris", duration_years=1.5, tuition_usd_year=21800, scholarship_available=False, description="English-taught MSc providing future managers and consultants with managerial and communication skills to act as change agents in global organisations.", field_of_study=["Business Analysis","Consulting","Change Management"]),
    dict(university="Tomorrow University of Applied Sciences", program_name="Impact MBA in Responsible Entrepreneurship and Technology", country="Germany", city="Online", duration_years=1.0, tuition_usd_year=None, scholarship_available=False, description="MBA reshaping the future business landscape through sustainable innovation and emerging technologies with an impact-first approach.", field_of_study=["Entrepreneurship","Technology Management","Sustainability"]),
    dict(university="University West", program_name="Cybersecurity", country="Sweden", city="Trollhättan", duration_years=1.0, tuition_usd_year=None, scholarship_available=False, description="One-year MSc covering risk management, compliance, law, regulations, security and hacking, and digital forensics for comprehensive cyber protection.", field_of_study=["Cybersecurity","Risk Management","Digital Forensics"]),
    dict(university="Charles University", program_name="Game Studies (GAME)", country="Czech Republic", city="Prague", duration_years=2.0, tuition_usd_year=7000, scholarship_available=False, description="Interdisciplinary MSc focusing on digital and non-digital games as a medium, building on media studies, sociology, anthropology, and film studies.", field_of_study=["Game Studies","Media Studies","Digital Culture"]),
    dict(university="NIT - Private Business School at Hamburg University of Technology (TUHH)", program_name="Business Analytics and Artificial Intelligence", country="Germany", city="Hamburg", duration_years=2.0, tuition_usd_year=14876, scholarship_available=False, description="Two-year MSc combining theory with practical application to harness the power of data and AI for solving real-world business problems.", field_of_study=["Business Analytics","Artificial Intelligence","Data Science"]),
    dict(university="Eindhoven University of Technology (TU/e)", program_name="Human-Technology Interaction - Mastertrack Robots for Humans", country="Netherlands", city="Eindhoven", duration_years=2.0, tuition_usd_year=2694, scholarship_available=False, description="MSc shedding light on how relationships with robots should be understood and designed, offering critical perspectives on the role of social robots in society.", field_of_study=["HCI","Robotics","Human-Robot Interaction"]),
]


def build_record(p: dict) -> dict:
    return {
        "university": p["university"],
        "program_name": p["program_name"],
        "country": p["country"],
        "city": p.get("city"),
        "category": "computer-science-it",
        "duration_years": p.get("duration_years"),
        "tuition_usd_year": p.get("tuition_usd_year"),
        "language": "English",
        "field_of_study": p.get("field_of_study", []),
        "scholarship_available": p.get("scholarship_available", False),
        "description": p.get("description", ""),
        "level": "master",
        "source_name": "mastersportal",
        "source_url": SOURCE_URL,
        "apply_url": "",
        "fingerprint": fp(p["program_name"], p["country"]),
    }


def main():
    records = [build_record(p) for p in PROGRAMS]
    print(f"Inserting {len(records)} programs...")

    # Batch insert in chunks of 50
    inserted = 0
    skipped = 0
    for i in range(0, len(records), 50):
        batch = records[i:i+50]
        r = httpx.post(
            f"{SB_URL}/rest/v1/masters_programs",
            headers=HEADERS,
            json=batch,
            timeout=30,
        )
        if r.status_code in (200, 201):
            inserted += len(batch)
        elif r.status_code == 409:
            # Some conflicts — try one by one
            for rec in batch:
                r2 = httpx.post(f"{SB_URL}/rest/v1/masters_programs", headers=HEADERS, json=[rec], timeout=15)
                if r2.status_code in (200, 201):
                    inserted += 1
                else:
                    skipped += 1
        else:
            print(f"  ERROR batch {i//50 + 1}: {r.status_code} {r.text[:200]}")

    print(f"Done. Inserted/updated: {inserted}  Skipped (duplicates): {skipped}")

    # Final count check
    h2 = {"apikey": SB_KEY, "Authorization": f"Bearer {SB_KEY}", "Prefer": "count=exact"}
    r = httpx.get(f"{SB_URL}/rest/v1/masters_programs", headers=h2, params={"source_name": "eq.mastersportal", "category": "eq.computer-science-it", "select": "id", "limit": "1"}, timeout=15)
    count = int(r.headers.get("content-range", "0/0").split("/")[-1])
    print(f"CS & IT mastersportal programs in DB: {count}")


if __name__ == "__main__":
    main()
