-- ============================================================
-- Seed: Computer Science & IT Master's programs from Mastersportal
-- Source: mastersportal.eu — pages 1–5 (~100 programs)
-- Run AFTER seed_masters.sql AND migrate_programs.sql
-- Safe to run multiple times — ON CONFLICT (fingerprint) DO NOTHING
-- ============================================================

INSERT INTO masters_programs (
  university, program_name, country, city, category,
  duration_years, tuition_usd_year, language,
  field_of_study, scholarship_available, description,
  level, source_name, source_url, apply_url, fingerprint
)
SELECT
  v.university, v.program_name, v.country, v.city, 'computer-science-it',
  v.duration_years, v.tuition_eur, 'English',
  v.fields, v.scholarship, v.description,
  'master', 'mastersportal',
  'https://www.mastersportal.eu/disciplines/34/computer-science-it.html', '',
  encode(sha256((lower(trim(v.program_name)) || '|' || lower(v.country) || '|master')::bytea), 'hex')
FROM (VALUES

-- ── PAGE 1 ────────────────────────────────────────────────────────────────
('Vita-Salute San Raffaele University','Health Informatics','Italy','Milano',2.0,6640,ARRAY['Health Informatics','Medical Data','Artificial Intelligence'],false,'MSc developing advanced informatics skills applied to medicine, preparing professionals for digital healthcare and medical AI roles.'),
('Marbella Design Academy','Innovative Design','Spain','Málaga',0.9,18000,ARRAY['Design','Innovation','Technology'],false,'Awarded as an official UK Master''s degree by University of Bedfordshire; studio-based programme on innovative design methods and technology.'),
('KU Leuven','Information Management','Belgium','Leuven',1.0,1181,ARRAY['Information Management','Business IT','Data Management'],false,'Non-technical MSc emphasising efficient application and management of information technology in business contexts including finance, HR, and logistics.'),
('Webster Geneva Campus','Business Administration with an Emphasis in Cybersecurity','Switzerland','Geneva',1.0,38426,ARRAY['Cybersecurity','Business Administration','Management'],false,'MBA with cybersecurity emphasis teaching business competencies needed to develop and implement value-creating solutions while managing digital risk.'),
('Radboud University','Language and Communication Technologies','Netherlands','Nijmegen',1.0,2694,ARRAY['Computational Linguistics','NLP','Language Technology'],false,'MSc focusing on improving linguistic and communicative properties of automatic language systems; ideal for students interested in NLP and AI.'),
('EAE Business School Barcelona Campus','Business Administration and AI Track','Spain','Barcelona',0.8,NULL,ARRAY['Business Administration','Artificial Intelligence','Management'],false,'MBA programme designed to accelerate professionals and entrepreneurs combining core business competencies with artificial intelligence applications.'),
('Vrije Universiteit Brussel (VUB)','Computer Science','Belgium','Brussels',2.0,1182,ARRAY['Computer Science','Software Engineering','Algorithms'],false,'Two-year MSc providing deep scientific understanding of computer science with specialised elective courses for academic bachelor holders.'),
('emlyon business school','Healthcare Innovation and Data Science','France','Lyon',2.0,19250,ARRAY['Healthcare IT','Data Science','Innovation Management'],false,'MSc meeting growing demand for digital transformation in healthcare, combining innovation management with advanced data science, analytics, and AI skills.'),
('Howest University of Applied Sciences','Advanced Bachelor of Bioinformatics','Belgium','Brugge',1.0,1200,ARRAY['Bioinformatics','Life Sciences','Data Science'],false,'One-year post-bachelor programme preparing graduates to operate at the intersection of life sciences and IT in one of the fastest-growing fields.'),
('JUNIA - Graduate School of Science and Engineering','Big Data','France','Lille',2.0,9770,ARRAY['Big Data','Artificial Intelligence','Machine Learning'],false,'MSc developing cutting-edge skills in AI and Big Data through advanced machine learning, NLP, computer vision, and cloud architecture with specialisation in Big Data or AI.'),
('Vrije Universiteit Brussel (VUB)','Applied Computer Science','Belgium','Brussels',2.0,1182,ARRAY['Computer Science','Data Science','Software Development'],false,'MSc developing computer and data science skills through specialised courses for students seeking practical computing expertise with academic depth.'),
('SupBiotech Paris','Biotechnology and AI','France','Paris',2.0,13950,ARRAY['Bioinformatics','Artificial Intelligence','Biotechnology'],false,'Cutting-edge programme designed by SupBiotech Paris in partnership with EPITA and ESME, training future bioinformatics and AI experts over two years.'),
('NOVA IMS','Data Science for Marketing','Portugal','Lisbon',2.0,3000,ARRAY['Data Science','Marketing Analytics','Machine Learning'],false,'MSc filling a gap in postgraduate training of marketing professionals needing analytical skills for data-driven marketing model development.'),
('Fresenius University of Applied Sciences','SAP Engineering and Analytics','Germany','Heidelberg',2.0,10560,ARRAY['SAP','Data Analytics','Digital Transformation'],false,'MSc empowering students to gain understanding of digital transformation, software engineering, and advanced data science with SAP technologies.'),
('Webster University Athens','Business Administration with an Emphasis in Cybersecurity','Greece','Athens',2.0,12480,ARRAY['Cybersecurity','Business Administration','Risk Management'],false,'Flexible MBA with cybersecurity specialisation offering small classes, personal attention, and a real-world approach to digital business security.'),
('Vrije Universiteit Brussel (VUB)','Geography','Belgium','Brussels',2.0,1182,ARRAY['Geography','GIS','Climate Science'],false,'MSc providing hands-on training in qualitative and quantitative geographical research with specialisation modules in Earth, Climate, and Geo-information Sciences.'),
('Utrecht University','Economics and Data Analysis','Netherlands','Utrecht',1.0,2694,ARRAY['Economics','Data Analysis','Econometrics'],false,'MSc providing solid theoretical foundation in microeconomics, macroeconomics, and econometrics for applied quantitative data analysis careers.'),
('EU Business School','Digital Business','Spain','Barcelona',1.0,16350,ARRAY['Digital Business','E-commerce','Business Strategy'],false,'MSc exploring the theoretical and practical foundations, implementation and business models that make up the digital business landscape.'),
('Utrecht University','Business Informatics','Netherlands','Utrecht',2.0,2694,ARRAY['Business IT','Information Systems','Data Management'],false,'MSc focusing on design and use of information and computing science theories applied in business and organisational domains with a holistic approach.'),
('JUNIA - Graduate School of Science and Engineering','Software Engineering and Information Systems','France','Lille',2.0,9770,ARRAY['Software Engineering','Information Systems','Web Development'],false,'MSc building strong skills in software engineering through web and mobile development, Java applications, object-oriented design, and quality-driven coding.'),

-- ── PAGE 2 ────────────────────────────────────────────────────────────────
('Utrecht University','Data Science','Netherlands','Utrecht',2.0,2694,ARRAY['Data Science','Machine Learning','Statistics'],false,'MSc teaching the principles and core fundamentals of data science including theories, tools, techniques, and methodologies for data-driven problem solving.'),
('Aeres University of Applied Sciences','Agribusiness Development','Netherlands','Dronten',1.0,2695,ARRAY['Agribusiness','Food Systems','Data Analytics'],false,'MSc preparing professionals for careers in international agribusiness companies focused on sustainable food production and supply chain management.'),
('University of Padua','ICT for Internet and Multimedia','Italy','Padova',2.0,2739,ARRAY['ICT','Multimedia','Internet Engineering'],false,'MSc capturing the evolution of information engineering with a modern approach combining solid fundamental knowledge and advanced technological skills.'),
('Pompeu Fabra University','EMAI - Erasmus Mundus Joint Master in Artificial Intelligence','Spain','Barcelona',2.0,9000,ARRAY['Artificial Intelligence','Machine Learning','Cognitive Science'],true,'Two-year Erasmus Mundus joint MSc funded by the European Commission providing comprehensive theory and practice in AI; scholarships available.'),
('EU Business School','Business Analytics and Data Science','Online','Online',1.0,16350,ARRAY['Business Analytics','Data Science','Machine Learning'],false,'Online MSc giving students a foundation in data science using industry-leading software, tools, and applications for data-driven business decisions.'),
('EADA Business School','Artificial Intelligence for Business','Spain','Barcelona',0.75,NULL,ARRAY['Artificial Intelligence','Business Strategy','Data Science'],false,'Nine-month MSc equipping students to lead in the data-driven future, combining AI technical skills with strategic leadership to optimise business operations.'),
('Hasselt University','Statistics and Data Science','Belgium','Hasselt',2.0,2699,ARRAY['Statistics','Data Science','Bioinformatics'],false,'Two-year MSc combining solid study of statistical principles and modern data science with a focus on life sciences applications including clinical trials and genomics.'),
('SBS Swiss Business School Barcelona','Business Analytics','Spain','Barcelona',1.0,17575,ARRAY['Business Analytics','Data Science','Strategy'],false,'MSc developing skills to understand business data and turn it into actionable insights, staying ahead of the curve in today''s data-driven business world.'),
('EU Business School','Artificial Intelligence for Business','Germany','Munich',1.0,16350,ARRAY['Artificial Intelligence','Business Strategy','Technology Management'],false,'MSc providing the opportunity to explore AI technology in depth across a range of business contexts at the Munich campus.'),
('USTP - University of Applied Sciences St. Pölten','Digital Innovation and Research','Austria','Sankt Pölten',2.0,726,ARRAY['Digital Innovation','Research Methods','Digitalization'],false,'MSc bridging applied research, innovation, and digitalisation for professionals passionate about leading digital transformation strategies.'),
('EU Business School','Business Analytics and Data Science','Spain','Barcelona',1.0,16350,ARRAY['Business Analytics','Data Science','Machine Learning'],false,'MSc giving students a comprehensive foundation in data science using industry-leading software, tools, and applications for the Barcelona campus.'),
('Universidade Nova de Lisboa - NOVA School of Law','Law Applied to Technology (Law and Tech)','Portugal','Lisbon',2.0,3600,ARRAY['Technology Law','Digital Law','Cybersecurity Policy'],false,'MSc focusing on digital and other emerging technological transformations, studying law in an international and comparative way.'),
('Utrecht University','Geographical Information Management and Applications (GIMA)','Netherlands','Utrecht',2.0,2694,ARRAY['GIS','Geoinformatics','Spatial Data'],false,'Two-year joint MSc in geo-information available in part-time and full-time modes, delivered with multiple Dutch universities.'),
('EU Business School','Business Analytics and Data Science','Germany','Munich',1.0,16350,ARRAY['Business Analytics','Data Science','Machine Learning'],false,'Hands-on MSc giving students a comprehensive foundation in data science using industry-leading software and applications at the Munich campus.'),
('Utrecht University','Human Computer Interaction','Netherlands','Utrecht',2.0,2694,ARRAY['HCI','UX Design','Cognitive Science'],false,'MSc exploring how computing devices can be adapted to individual users and how to develop new approaches to human-machine interaction.'),
('University College Dublin','Human Computer Interaction','Ireland','Dublin',1.0,9515,ARRAY['HCI','UX','Information Studies'],false,'MSc combining core HCI elements from a social science perspective, harnessing expertise in the School of Information and Communication Studies.'),
('Vlerick Business School','Business Analytics and AI','Belgium','Gent',0.8,NULL,ARRAY['Business Analytics','Artificial Intelligence','Data Strategy'],false,'Ten-month MSc combining analytical and strategic foundations to translate data and AI into real business value with leadership skills.'),
('Global Banking School Malta','Master of Science in Information Technology Management','Malta','San Gwann',1.0,10000,ARRAY['IT Management','Cybersecurity','Data Analytics'],false,'MSc addressing growth in the IT industry, focusing on technology infrastructure from IT service desk support to data-driven executive decision-making.'),
('Vrije Universiteit Brussel (VUB)','Applied Informatics - Artificial Intelligence and Data Science','Belgium','Brussels',1.0,1182,ARRAY['Artificial Intelligence','Data Science','Software Development'],false,'MSc enabling students to master practical aspects of informatics, preparing for jobs in software development, data processing, and system analysis.'),
('NEOMA Business School','Artificial Intelligence for Business','France','Rouen',1.25,15600,ARRAY['Artificial Intelligence','Business Strategy','Digital Transformation'],false,'MSc training professionals to create, manage, and implement AI solutions within organisations for competitive advantage.'),

-- ── PAGE 3 ────────────────────────────────────────────────────────────────
('EAE Business School Barcelona Campus','Big Data and Analytics','Spain','Barcelona',0.8,NULL,ARRAY['Big Data','Analytics','Business Intelligence'],false,'MSc offering complete training for professionals in big data and analytics, covering the most in-demand market skills.'),
('University College Dublin','Information Systems','Ireland','Dublin',1.0,9515,ARRAY['Information Systems','IT Management','Business Analytics'],false,'MSc incorporating information technology and data analytics with a grounding in social science for well-rounded IS professionals.'),
('University College Dublin','Library and Information Studies','Ireland','Dublin',1.0,9515,ARRAY['Library Science','Information Management','Digital Libraries'],false,'MSc preparing graduates for professional settings including academic, public, and special libraries as well as information-based roles in various sectors.'),
('EU Business School','Artificial Intelligence for Business','Spain','Barcelona',1.0,10900,ARRAY['Artificial Intelligence','Business Strategy','Innovation'],false,'MSc exploring AI technology in depth across a range of business contexts at the Barcelona campus.'),
('SDA Bocconi School of Management','Master in Sustainability Management','Italy','Milan',1.0,30000,ARRAY['Sustainability','ESG','Data Analytics'],false,'MSc from SDA Bocconi addressing sustainability, climate change, biodiversity, and energy challenges for governments, companies, and civil society.'),
('EAE Business School Barcelona Campus','International Business STEM','Spain','Barcelona',0.8,NULL,ARRAY['International Business','Technology','STEM'],false,'MSc preparing professionals to navigate global markets and lead enterprises in an interconnected, tech-driven world.'),
('USTP - University of Applied Sciences St. Pölten','Cyber Security and Resilience','Austria','Sankt Pölten',2.0,726,ARRAY['Cybersecurity','Resilience Engineering','Information Security'],false,'Two-year MSc teaching how to build and run resilient information systems, covering secure architecture, risk management, and cyber defence.'),
('NEOMA Business School','Business Analytics','France','Rouen',1.25,15600,ARRAY['Business Analytics','Data Science','Strategic Decision Making'],false,'MSc equipping students with skills and knowledge to transform complex data into actionable insights for strategic decision-making.'),
('USTP - University of Applied Sciences St. Pölten','Joint Master in Applied XR - Gamified Reality Applications for Real-world Challenges and Experiences (GRACE)','Austria','Sankt Pölten',2.0,726,ARRAY['Extended Reality','XR','Game Design','Innovation'],false,'Joint MSc in Applied XR featuring real-world projects guided by an international mentor network, turning innovation into impact across industries.'),
('ESIEE Paris - Université Gustave Eiffel','Management of Technology - Information Systems','France','Paris',1.5,7000,ARRAY['IT Management','Information Systems','Project Management'],false,'MSc taught entirely in English equipping students to become international project managers working at the interface of management and technology.'),
('ESSCA School of Management','Business Analytics','France','Boulogne-Billancourt',1.0,21800,ARRAY['Business Analytics','Finance','Artificial Intelligence'],false,'MSc combining the power of data, finance, and artificial intelligence into a single future-oriented programme for analytical business leaders.'),
('Utrecht University','Computing Science','Netherlands','Utrecht',2.0,2694,ARRAY['Computer Science','Theory','Algorithms'],false,'MSc allowing students to dive into the depths of fundamental computing science, exploring theoretical and applied aspects of the discipline.'),
('Free University of Bozen-Bolzano','Software Engineering','Italy','Bolzano',2.0,1200,ARRAY['Software Engineering','Cloud Computing','IoT'],false,'MSc leveraging next-generation technologies including Cloud Computing, IoT, and Analytics to create and engineer innovative information systems.'),
('University of Padua','Complex and Data Driven Chemistry','Italy','Padova',2.0,2739,ARRAY['Computational Chemistry','Data Science','Chemometrics'],false,'MSc introducing fundamental concepts of data-driven chemistry including statistical learning, chemometrics, and design of experiments.'),
('Free University of Bozen-Bolzano','Computing for Data Science','Italy','Bolzano',2.0,1200,ARRAY['Data Science','Information Systems','Machine Learning'],false,'MSc providing key competencies to develop next-generation information systems for data management, fact discovery, prediction, and decision support.'),
('Free University of Bozen-Bolzano','Data Analytics for Economics and Management','Italy','Bolzano',2.0,1200,ARRAY['Data Analytics','Economics','Management Science'],false,'MSc designed for students developing state-of-the-art skills in computing, econometrics, statistics, and mathematics for economic data analysis.'),
('LUMSA University','Financial Data Analytics and Sustainable Finance (FINDATA)','Italy','Rome',1.0,6000,ARRAY['Financial Analytics','Sustainable Finance','Data Science'],false,'Joint MSc organised by four European universities: University of Pardubice, European University Cyprus, LUMSA, and Vilnius University.'),
('LUMSA University','Management, Finance and Data Analytics','Italy','Rome',2.0,4390,ARRAY['Management','Finance','Data Analytics'],false,'MSc training graduates with skills in management, finance, and data analysis to operate as managers, consultants, and analysts.'),
('LUMSA University','AI for Marketing and Communication','Italy','Rome',2.0,4390,ARRAY['Artificial Intelligence','Marketing','Digital Communication'],false,'MSc providing comprehensive study of marketing and communication theory combined with practical AI tools for traditional and digital media.'),
('Universidad Europea','Business Analytics and Business Intelligence','Spain','Madrid',0.75,NULL,ARRAY['Business Analytics','Business Intelligence','Data Management'],false,'Nine-month MSc focusing on collecting, structuring, and analysing company data to optimise decision-making with BI tools.'),

-- ── PAGE 4 ────────────────────────────────────────────────────────────────
('Constructor University','Data Science for Society and Business','Germany','Bremen',2.0,20000,ARRAY['Data Science','Social Science','Business Analytics'],false,'Highly selective two-year MSc for business and social science students aiming to become data science experts in applied organisational contexts.'),
('Radboud University','Cyber Security','Netherlands','Nijmegen',2.0,2695,ARRAY['Cybersecurity','Security Analysis','Cryptography'],false,'MSc teaching how to assess the security of existing ICT systems and develop more secure future solutions as reliance on IT increases.'),
('Roskilde University','Computer Science','Denmark','Roskilde',2.0,NULL,ARRAY['Computer Science','Software Development','System Design'],false,'Practice-oriented MSc focusing on developing complex, reliable, user-friendly, and long-lasting IT systems; tuition-free for EU/EEA students.'),
('Turiba University','Information Technology','Latvia','Riga',1.5,3090,ARRAY['Information Technology','IT Management','Networking'],false,'MSc providing comprehensive knowledge of the global IT world and its development, fostering professional growth in technology management.'),
('Masaryk University','Artificial Intelligence and Data Processing','Czech Republic','Brno',2.0,4500,ARRAY['Artificial Intelligence','Data Processing','Machine Learning'],false,'MSc preparing students for design and development of intelligent systems and big data analysis in this rapidly developing field.'),
('Reykjavík University','Digital Management and Data Analysis','Iceland','Reykjavík',1.0,11067,ARRAY['Digital Management','Data Analysis','Innovation'],false,'MSc equipping graduates with cutting-edge interdisciplinary expertise in digital management and data analysis that is highly sought after across industries.'),
('Wageningen University and Research','Data Science for Food and Health','Netherlands','Wageningen',2.0,2694,ARRAY['Data Science','Food Science','Health Analytics'],false,'MSc integrating data science with food and health domains, using data-driven approaches to solve complex questions in nutrition and food systems.'),
('LUT University','Software Product Management and Business','Finland','Lahti',2.0,NULL,ARRAY['Software Management','Product Development','Business'],false,'MSc focusing on design, implementation, and maintenance of software and digital services in their business context; tuition-free for EU students.'),
('Technological University of the Shannon','Software Engineering','Ireland','Athlone',1.0,5880,ARRAY['Software Engineering','Research','Software Quality'],false,'MSc enhancing knowledge and expertise in active research and development areas of software engineering for computer professionals.'),
('Lancaster University Leipzig','Data Science','Germany','Leipzig',1.0,16600,ARRAY['Data Science','Machine Learning','Analytics'],false,'MSc ensuring advanced skills, knowledge, and experience in this rapidly expanding, highly in-demand field to achieve career aspirations.'),
('HTW Berlin','Project Management and Data Science','Germany','Berlin',2.0,8800,ARRAY['Project Management','Data Science','International Business'],false,'International MSc preparing students with academic knowledge, real-world experience, and industry connections for managing data-driven projects.'),
('GBSB Global Business School','Blockchain Management','Malta','Birkirkara',1.0,7750,ARRAY['Blockchain','Cryptocurrency','Digital Finance'],false,'MSc providing deep understanding of blockchain from its origins in cryptocurrency to its broader applications in securing digital transactions.'),
('Radboud University','Software Science','Netherlands','Nijmegen',2.0,2695,ARRAY['Software Engineering','Code Analysis','Formal Methods'],false,'MSc specialisation focusing on analysing and testing code in order to both improve and simplify it for more reliable software systems.'),
('University College Cork','Mathematical Modelling and Machine Learning','Ireland','Cork',1.0,8000,ARRAY['Machine Learning','Mathematical Modelling','Numerical Methods'],false,'MSc providing training in the use and development of modern numerical methods and machine-learning software for applied research.'),
('Wageningen University and Research','Geographical Information Management and Applications','Netherlands','Wageningen',2.0,2694,ARRAY['GIS','Geoinformatics','Spatial Data Science'],false,'Joint MSc delivered by Wageningen, TU Delft, Utrecht University, and University of Twente — geo-information experts from four universities.'),
('Tomorrow University of Applied Sciences','Impact MSc in Data Leadership in Sustainable Innovation','Germany','Online',1.5,NULL,ARRAY['Data Leadership','Sustainability','Digital Innovation'],false,'MSc equipping students to manage data-driven sustainability projects, craft impactful strategies, and lead sustainability initiatives with technology.'),
('Fresenius University of Applied Sciences','Computer Science','Germany','Berlin',2.0,10560,ARRAY['Computer Science','Cybersecurity','Artificial Intelligence'],false,'MSc for digital experts deepening methodological and technological knowledge in Cyber Security and Artificial Intelligence through German study.'),
('University of Vaasa','Industrial Systems Analytics','Finland','Vaasa',2.0,NULL,ARRAY['Systems Analytics','Energy Technology','Industrial Engineering'],false,'MSc preparing future leaders in energy and technology sectors by combining engineering expertise with practical business and operational excellence.'),
('Jönköping University','Cybersecurity (one year)','Sweden','Jönköping',1.0,NULL,ARRAY['Cybersecurity','Risk Management','Digital Forensics'],false,'One-year MSc designed to complement a Bachelor''s degree with the latest cybersecurity advances for digitalization projects across industries.'),
('Technological University of the Shannon','Data Analytics (Athlone)','Ireland','Athlone',1.0,7000,ARRAY['Data Analytics','Big Data','Business Intelligence'],false,'Industry-focused MSc equipping graduates with skills and aptitudes necessary to excel in the emerging field of Big Data and Data Analytics.'),

-- ── PAGE 5 ────────────────────────────────────────────────────────────────
('Università Cattolica del Sacro Cuore','Data Analytics for Business','Italy','Milan',2.0,6850,ARRAY['Data Analytics','Business','Statistics'],false,'MSc offered jointly with the Faculty of Mathematics, Physics and Natural Sciences combining quantitative analysis with business applications.'),
('Northumbria University','Computing and Technology','Netherlands','Amsterdam',1.0,24891,ARRAY['Computing','IT Management','Digital Leadership'],false,'MSc designed to update, extend and deepen knowledge in computing, IT, and wider digital leadership subjects to enhance career opportunities.'),
('University of Pécs','Computer Science Engineering','Hungary','Pécs',2.0,6891,ARRAY['Computer Science','Engineering','Information Technology'],false,'MSc providing engineers from technical IT disciplines with skills to pursue a career in computer and information engineering.'),
('ESCP Business School','Strategy and Digital Business','France','Paris',2.0,NULL,ARRAY['Digital Strategy','Business Management','Innovation'],false,'Rigorous two-year programme equipping students with strategic, digital, and entrepreneurial skills demanded by today''s job markets.'),
('Masaryk University','Computer Systems, Communication and Security','Czech Republic','Brno',2.0,4500,ARRAY['Systems Security','Networking','Computer Architecture'],false,'MSc leading graduates to understanding of architectures, principles, and design methods for secure computer systems including network communications.'),
('Radboud University','Artificial Intelligence - Human Centered Intelligent Systems','Netherlands','Nijmegen',2.0,2695,ARRAY['Artificial Intelligence','HCI','Medical AI'],false,'Interdisciplinary MSc specialisation studying and developing intelligent systems from medical AI to artificial agents and human-machine interfaces.'),
('Kaunas University of Technology','Artificial Intelligence in Computer Science','Lithuania','Kaunas',2.0,5538,ARRAY['Artificial Intelligence','Computer Science','Machine Learning'],false,'MSc convening competences for students to actively contribute to improvement and innovation in the rapidly developing field of AI and informatics.'),
('Radboud University','Cyber Security and AI','Netherlands','Nijmegen',2.0,2695,ARRAY['Cybersecurity','Artificial Intelligence','Security Engineering'],false,'Unique MSc programme exploring the interplay between AI and Cyber Security, covering the latest approaches and challenges of both domains.'),
('University College Cork','Cybersecurity','Ireland','Cork',1.0,8000,ARRAY['Cybersecurity','Security Engineering','Digital Forensics'],false,'MSc providing in-depth understanding of practical and theoretical aspects of cybersecurity for securing digital systems that operate 24x7.'),
('Warsaw University of Technology','Mobile Mapping and Navigation Systems','Poland','Warsaw',1.5,3600,ARRAY['Geomatics','Navigation','Spatial Data'],false,'MSc in Geodesy and Cartography specialisation on collecting, processing, and analysing spatial data for modern navigation systems.'),
('Atlantic Technological University','Computing','Ireland','Galway',1.0,6300,ARRAY['Computing','Software Development','Technology Management'],false,'MSc enabling graduates and professionals to develop advanced thinking and technical know-how in a range of technology-centric disciplines.'),
('GBSB Global Business School','Enterprise Cybersecurity Management','Spain','Madrid',0.75,NULL,ARRAY['Cybersecurity','Enterprise Security','Governance'],false,'Nine-month MSc preparing graduates to transform governance into action through enterprise cybersecurity management and strategic security leadership.'),
('Écoles d''Ingénieurs - Engineering School (ECE)','Data and AI','France','Bordeaux',2.0,10950,ARRAY['Data Science','Artificial Intelligence','Machine Learning'],false,'MSc mastering Machine Learning algorithms and data analysis tools (R, Spark, Python, Matlab) with focus on real-world data and AI applications.'),
('Jönköping University','Software Engineering for AI','Sweden','Jönköping',2.0,NULL,ARRAY['Software Engineering','Artificial Intelligence','System Design'],false,'Two-year MSc from an international university known for student entrepreneurship, strong research, and successful industry collaborations in AI engineering.'),
('IÉSEG School of Management','Business Analysis and Consulting','France','Paris',1.5,21800,ARRAY['Business Analysis','Consulting','Change Management'],false,'English-taught MSc providing future managers and consultants with managerial and communication skills to act as change agents in global organisations.'),
('Tomorrow University of Applied Sciences','Impact MBA in Responsible Entrepreneurship and Technology','Germany','Online',1.0,NULL,ARRAY['Entrepreneurship','Technology Management','Sustainability'],false,'MBA reshaping the future business landscape through sustainable innovation and emerging technologies with an impact-first approach.'),
('University West','Cybersecurity','Sweden','Trollhättan',1.0,NULL,ARRAY['Cybersecurity','Risk Management','Digital Forensics'],false,'One-year MSc covering risk management, compliance, law, regulations, security and hacking, and digital forensics for comprehensive cyber protection.'),
('Charles University','Game Studies (GAME)','Czech Republic','Prague',2.0,7000,ARRAY['Game Studies','Media Studies','Digital Culture'],false,'Interdisciplinary MSc focusing on digital and non-digital games as a medium, building on media studies, sociology, anthropology, and film studies.'),
('NIT - Private Business School at Hamburg University of Technology (TUHH)','Business Analytics and Artificial Intelligence','Germany','Hamburg',2.0,14876,ARRAY['Business Analytics','Artificial Intelligence','Data Science'],false,'Two-year MSc combining theory with practical application to harness the power of data and AI for solving real-world business problems.'),
('Eindhoven University of Technology (TU/e)','Human-Technology Interaction - Mastertrack Robots for Humans','Netherlands','Eindhoven',2.0,2694,ARRAY['HCI','Robotics','Human-Robot Interaction'],false,'MSc shedding light on how relationships with robots should be understood and designed, offering critical perspectives on the role of social robots in society.')

) AS v(university, program_name, country, city, duration_years, tuition_eur, fields, scholarship, description)
ON CONFLICT (fingerprint) DO NOTHING;
