-- ============================================================
-- Seed: Agriculture & Forestry Master's programs from Mastersportal
-- Source: mastersportal.eu — pages 11–16 (~96 programs)
-- Run AFTER seed_masters.sql AND migrate_programs.sql
-- Safe to run multiple times — ON CONFLICT (fingerprint) DO NOTHING
-- ============================================================

INSERT INTO masters_programs (
  university, program_name, country, city, category,
  duration_years, tuition_usd_year, language,
  field_of_study, scholarship_available, description,
  level, source_name, source_url, apply_url, fingerprint
)
SELECT
  v.university, v.program_name, v.country, v.city, 'agriculture',
  v.duration_years, v.tuition_eur, 'English',
  v.fields, v.scholarship, v.description,
  'master', 'mastersportal',
  'https://www.mastersportal.eu/disciplines/0/agriculture-forestry.html', '',
  encode(sha256((lower(trim(v.program_name)) || '|' || lower(v.country) || '|master')::bytea), 'hex')
FROM (VALUES

-- ── PAGE 11 ────────────────────────────────────────────────────────────────
('University College Dublin','Animal Science (Online)','Ireland','Dublin',1.0,10430,ARRAY['Animal Science','Biology','Sustainability'],false,'Online MSc in Animal Science from UCD designed for professionals in the livestock sector covering animal nutrition, production, and welfare.'),
('University of Agriculture in Krakow','Horticultural Science','Poland','Kraków',2.0,NULL,ARRAY['Agriculture','Horticulture','Plant Science'],false,'MSc training specialists for management, trade, and governmental services in horticulture at European level; tuition-free for EU students.'),
('University of Bologna','Food and Wine','Italy','Bologna',1.0,35000,ARRAY['Food Science','Wine Studies','Business'],false,'Global MBA in Food and Wine training managers for the growth and internationalisation of companies in the food and beverage industry.'),
('University of Agriculture in Krakow','Food Engineering','Poland','Kraków',2.0,2800,ARRAY['Food Science','Engineering','Technology'],false,'MSc in food processing technology concluding with a research-based master thesis in English; graduates work in the food and processing industry.'),
('Bern University of Applied Sciences','Life Sciences - Forest Science','Switzerland','Bern',1.5,2079,ARRAY['Forestry','Life Sciences','Environmental Science'],false,'MSc equipping graduates with knowledge of forest ecology, wood production, and sustainable management for careers in forest science.'),
('University of Zagreb','Close to Nature Forestry','Croatia','Zagreb',2.0,4100,ARRAY['Forestry','Ecology','Natural Resource Management'],false,'MSc in close-to-nature forestry approaches combining silviculture, biodiversity, and sustainable forest management principles.'),
('Warsaw University of Life Sciences','Sustainable Horticulture','Poland','Warsaw',2.0,1792,ARRAY['Agriculture','Horticulture','Sustainability'],false,'MSc educating specialists in integrated and organic horticulture, modern production technologies, pest management, and environmental protection.'),
('Slovak University of Agriculture in Nitra','Food Safety and Control','Slovakia','Nitra',2.0,1500,ARRAY['Food Science','Food Safety','Quality Control'],false,'MSc covering microbiological and chemical food safety with an integrated farm-to-fork approach to safe food production.'),
('Slovak University of Agriculture in Nitra','International Master of Horticulture Science','Slovakia','Nitra',2.0,2200,ARRAY['Agriculture','Horticulture','International Studies'],false,'Accredited joint MSc in horticulture science implemented by the Faculty of Horticulture and Landscape Engineering in Nitra.'),
('University of Galway','Coastal and Marine Environments - Physical Processes, Policy and Practice','Ireland','Galway',1.0,8000,ARRAY['Marine Science','Coastal Management','Environmental Policy'],false,'MSc for geography and natural science graduates focusing on physical processes, policy, and practice in coastal and marine environments.'),
('University of Zagreb','Environment, Agriculture and Resource Management','Croatia','Zagreb',2.0,NULL,ARRAY['Agriculture','Environmental Science','Resource Management'],false,'MSc enabling continuation of undergraduate studies with a focus on sustainable management of agricultural and environmental resources.'),
('University of Debrecen','Agricultural Environmental Management Engineering','Hungary','Debrecen',2.0,6888,ARRAY['Agriculture','Environmental Science','Engineering'],false,'MSc developing knowledge in agricultural environmental management, sustainable land use, and applied engineering solutions.'),
('University of Debrecen','Animal Husbandry Engineering','Hungary','Debrecen',2.0,6888,ARRAY['Animal Science','Engineering','Agriculture'],false,'MSc in animal husbandry covering production systems, animal science, technology, and economics for careers in the livestock sector.'),
('University of Debrecen','Food Safety and Quality Engineering','Hungary','Debrecen',2.0,6888,ARRAY['Food Science','Food Safety','Engineering'],false,'MSc in food safety and quality engineering equipping graduates with skills for roles in food industry quality assurance and regulation.'),
('Mendel University in Brno','European Forestry','Czech Republic','Brno',2.0,2677,ARRAY['Forestry','Environmental Science','Sustainability'],false,'MSc on the European concept of professional forest management within the context of resource and environmental planning of sustainable systems.'),
('University of Padua','MEDFOR - Mediterranean Forestry and Natural Resources Management','Italy','Padova',2.0,3000,ARRAY['Forestry','Natural Resource Management','Mediterranean Ecology'],true,'Two-year international MSc on sustainable Mediterranean forestry addressing economic, ecological and social challenges; Erasmus Mundus with scholarship support.'),
('Poznan University of Life Sciences','Animal Production Management','Poland','Poznan',2.0,2475,ARRAY['Animal Science','Agriculture','Management'],false,'MSc integrating environmental knowledge and technical measures to improve animal production while reducing environmental impact.'),
('Catholic University of Portugal','Food Engineering','Portugal','Lisbon',2.0,4590,ARRAY['Food Science','Engineering','Technology'],false,'MSc encompassing food engineering theory, project work, and industrial placement options with a focus on original research or industry practice.'),

-- ── PAGE 12 ────────────────────────────────────────────────────────────────
('The University of Oviedo','Marine Conservation','Spain','Oviedo',1.0,1560,ARRAY['Marine Science','Conservation','Biology'],false,'MSc in marine conservation offered by the Faculty of Biology, covering biodiversity assessment, marine protected areas, and conservation policy.'),
('Universidade Nova de Lisboa','Precision Agriculture Technologies','Portugal','Lisbon',2.0,2000,ARRAY['Agriculture','Precision Farming','Technology'],false,'MSc filling the postgraduate gap in precision agriculture, covering sensors, data analytics, and smart farming technologies.'),
('AgroParisTech','Food Innovation and Product Design','France','Paris',2.0,4500,ARRAY['Food Science','Innovation','Product Design'],true,'Erasmus Mundus joint MSc providing top-level education in food innovation, product design, and packaging for the global food industry.'),
('University of Sassari','Wildlife Management, Conservation, and Control','Italy','Sassari',2.0,NULL,ARRAY['Wildlife Management','Conservation','Environmental Science'],false,'MSc creating wildlife managers with skills in sustainable management of terrestrial and aquatic faunal resources in the Mediterranean region.'),
('The University of Oviedo','Marine Biological Resources (IMBRSea)','Spain','Oviedo',2.0,6000,ARRAY['Marine Science','Biology','Resource Management'],false,'Joint MSc in Marine Biological Resources organised by eleven European universities and supported by the European Marine Biological Resource Centre (EMBRC).'),
('University of Bologna','Precise and Sustainable Agriculture','Italy','Bologna',2.0,157,ARRAY['Agriculture','Precision Farming','Sustainability'],false,'MSc building experts in precision and sustainable agriculture techniques for plant or animal production systems.'),
('University of Bologna','Food Animal Metabolism and Management in the Circular Economy','Italy','Bologna',2.0,157,ARRAY['Animal Science','Food Science','Circular Economy'],false,'MSc training specialists in management of animal production systems within a circular economic approach.'),
('Szent István University','Agricultural Water Management Engineering','Hungary','Budapest',2.0,6000,ARRAY['Agriculture','Water Management','Engineering'],false,'MSc training professionals in agricultural water management with a focus on sustainable integrated water resources management.'),
('Czech University of Life Sciences Prague','Agricultural Sciences and Farming Systems in the Tropics and Subtropics - double degree','Czech Republic','Prague',2.0,535,ARRAY['Agriculture','Tropical Agriculture','International Studies'],false,'Unique double degree MSc allowing students to receive two master''s degrees in agricultural sciences in the tropics and subtropics within two years.'),
('Transilvania University of Brasov','European Forestry','Romania','Brasov',2.0,764,ARRAY['Forestry','Sustainability','Bioeconomy'],false,'Two-year interdisciplinary MSc in sustainable resource management with an emphasis on current bioeconomy issues in European forests.'),
('University of Natural Resources and Life Sciences Vienna','Organic Agricultural Systems and Agroecology (EUR-Organic)','Austria','Vienna',2.0,726,ARRAY['Agriculture','Organic Farming','Agroecology'],false,'MSc linking ecological, economic, political, and cultural characteristics of sustainable land-use systems across European organic farming networks.'),
('University of Natural Resources and Life Sciences Vienna','Mountain Forestry','Austria','Vienna',2.0,726,ARRAY['Forestry','Mountain Ecology','Natural Resource Management'],false,'Specialised MSc in managing mountain forest resources with a global perspective on climate adaptation and sustainable silviculture.'),
('University of Copenhagen','Agriculture','Denmark','Copenhagen',2.0,NULL,ARRAY['Agriculture','Plant Science','Sustainability'],false,'MSc focused on sustainable production of high-quality food for a growing population, shaping the future of plant science and agronomy; tuition-free for EU students.'),
('JUNIA - Graduate School of Science and Engineering','Innovation and Management in the Food Industry','France','Lille',2.0,9770,ARRAY['Food Science','Innovation','Management'],false,'MSc combining food biochemistry, microbiology, and nutrition with quality management and bioprocesses for careers in the global food industry.'),
('Technical University of Denmark','Food Technology','Denmark','Kongens Lyngby',2.0,NULL,ARRAY['Food Science','Technology','Sustainability'],false,'MSc providing deep knowledge of technologies associated with the production of healthy and safe food using modern food production systems; tuition-free for EU students.'),
('University of Hamburg','Polar and Marine Sciences (POMOR)','Germany','Hamburg',2.0,NULL,ARRAY['Marine Science','Polar Science','Environmental Science'],false,'Research-oriented MSc in polar and marine sciences covering Arctic/Antarctic ecosystems, climate dynamics, and ocean-ice interactions; tuition-free.'),
('Eberswalde University for Sustainable Development','Forest Information Technology','Germany','Eberswalde',2.0,NULL,ARRAY['Forestry','Information Technology','Environmental Science'],false,'MSc training IT specialists with a focus on forest and environmental monitoring using geospatial technologies and data systems; tuition-free.'),
('Aarhus University','Molecular Nutrition and Food Technology','Denmark','Aarhus',2.0,NULL,ARRAY['Food Science','Nutrition','Biotechnology'],false,'MSc exploring the link between food composition and human health through molecular nutrition science and food technology; tuition-free for EU students.'),
('Stockholm University','Marine Biology','Sweden','Stockholm',2.0,NULL,ARRAY['Marine Science','Biology','Ecology'],false,'MSc on marine ecosystems in the Baltic Sea and beyond, covering marine biodiversity, physiology, and ocean processes; tuition-free for EU students.'),

-- ── PAGE 13 ────────────────────────────────────────────────────────────────
('University of Lorraine','Forests and their Environments','France','Nancy',2.0,480,ARRAY['Forestry','Environmental Science','Ecology'],false,'MSc training students to integrate societal demands regarding sustainable forest management, ecosystem services, and technological solutions.'),
('University of Bremen','Marine Microbiology','Germany','Bremen',1.5,NULL,ARRAY['Marine Science','Microbiology','Biology'],false,'MSc enabling students to develop innovative approaches for environmental problems and contribute to fundamental marine microbial science; tuition-free.'),
('University of Pau and Pays de l''Adour','Evolutionary ecology in aquatic environments','France','Anglet',2.0,254,ARRAY['Marine Science','Ecology','Evolution'],false,'MSc training scientific experts to design experiments and models in evolutionary ecology relevant to aquatic ecosystem management.'),
('University of Gothenburg','Marine Science','Sweden','Göteborg',2.0,NULL,ARRAY['Marine Science','Oceanography','Environmental Science'],false,'Interdisciplinary MSc providing broad knowledge of the ocean as a system, developing analytical abilities for solving tomorrow''s marine science problems; tuition-free for EU students.'),
('University of Galway','AgriFood Sustainability and Technology','Ireland','Galway',1.0,8750,ARRAY['Agriculture','Food Science','Sustainability'],false,'MSc developing graduates with interdisciplinary skills to address agrifood sustainability and technology challenges in Ireland and globally.'),
('Justus Liebig University Giessen','Insect Biotechnology and Bioresources','Germany','Gießen',2.0,NULL,ARRAY['Agriculture','Biotechnology','Entomology'],false,'MSc in insect biotechnology exploring the use of insects as sustainable protein sources, biocontrol agents, and bioresource producers; tuition-free.'),
('University of Bordeaux','Marine EnviRonment 2030 (MER2030)','France','Bordeaux',2.0,4500,ARRAY['Marine Science','Environmental Science','Research'],false,'Postgraduate degree with a strong research element at internationally recognised training centres in marine science and environmental monitoring.'),
('Humboldt University Berlin','Integrated Natural Resource Management','Germany','Berlin',2.0,NULL,ARRAY['Natural Resource Management','Sustainability','Environmental Science'],false,'MSc enabling students to contribute towards the implementation of the UN SDGs through integrated research and practice in natural resource management; tuition-free.'),
('Eberswalde University for Sustainable Development','Forestry System Transformation','Germany','Eberswalde',2.0,NULL,ARRAY['Forestry','Sustainability','Ecosystem Management'],false,'MSc on modern forest ecosystem cultivation adapted to the social and ecological challenges of climate change and sustainable land use; tuition-free.'),
('University of Veterinary Medicine Vienna','Interdisciplinary Master''s Programme in Human-Animal Interactions','Austria','Vienna',2.0,NULL,ARRAY['Animal Science','Behaviour','Welfare'],false,'MSc addressing scientific research in behavioural biology, animal husbandry, welfare, philosophy, psychology, and neuroscience; tuition-free.'),
('Ghent University','Marine Biological Resources (IMBRSea)','Belgium','Gent',2.0,4500,ARRAY['Marine Science','Biology','Resource Management'],false,'Joint MSc in Marine Biological Resources organised by ten leading European universities, supported by the European Marine Biological Resource Centre (EMBRC).'),
('University of Kassel','Agriculture, Ecology and Societies','Germany','Kassel',2.0,782,ARRAY['Agriculture','Ecology','Sustainability'],false,'MSc training change-makers focused on Europe''s role in the worldwide socio-ecological transition to sustainable agriculture.'),
('Erasmus University Rotterdam','Maritime Economics and Logistics','Netherlands','Rotterdam',1.0,30950,ARRAY['Marine Science','Economics','Logistics'],false,'MSc providing outstanding qualifications in maritime economics and logistics for careers in shipping, ports, and maritime industries.'),
('Dundalk Institute of Technology','Agricultural Biotechnology','Ireland','Dundalk',1.0,7650,ARRAY['Agriculture','Biotechnology','Life Sciences'],false,'MSc providing deep knowledge of biotechnology applications in agriculture including animal genetics, crop production, and bioremediation.'),
('University of Natural Resources and Life Sciences Vienna','Organic Agricultural Systems and Agroecology','Austria','Vienna',2.0,726,ARRAY['Agriculture','Organic Farming','Agroecology'],false,'MSc offering education in all aspects of the organic sector with specialisation profiles from partner universities across Europe.'),
('Swedish University of Agricultural Sciences','Forest Bioeconomy','Sweden','Skara',2.0,NULL,ARRAY['Forestry','Bioeconomy','Sustainability'],false,'MSc opening careers in forestry, consulting, and green bioeconomy through knowledge of sustainable forest resource use and biomass production; tuition-free for EU students.'),
('University of Tübingen','Cellular and Immunological Biosciences - From Single Cells to Plants, Animals and Humans','Germany','Tübingen',2.0,NULL,ARRAY['Life Sciences','Biotechnology','Agriculture'],false,'Interdisciplinary MSc applying cellular and immunological approaches to current challenges across plant science, animal biology, and human health; tuition-free.'),
('University of Natural Resources and Life Sciences Vienna','Animal Breeding and Genetics (Joint degree)','Austria','Vienna',2.0,726,ARRAY['Animal Science','Genetics','Biotechnology'],false,'Joint degree MSc focused on developing sustainable breeding programmes for farm animals, fish, and companion animals using modern genomics.'),
('University of Natural Resources and Life Sciences Vienna','Horticultural Sciences','Austria','Vienna',2.0,726,ARRAY['Agriculture','Horticulture','Food Science'],false,'MSc on supply chains in horticulture, fruit growing, and viticulture with emphasis on processing, quality management, and marketing.'),
('Wroclaw University of Environmental and Life Sciences','Food Technology','Poland','Wroclaw',1.5,NULL,ARRAY['Food Science','Technology','Engineering'],false,'Double diploma MSc in food technology taught in English in cooperation with University Miguel Hernandez of Elche, Spain; tuition-free for EU students.'),

-- ── PAGE 14 ────────────────────────────────────────────────────────────────
('Universidade Nova de Lisboa','Maritime Logistics','Portugal','Lisbon',1.0,12000,ARRAY['Marine Science','Logistics','Management'],false,'Innovative joint MSc in maritime logistics delivered by NOVA FCT and the Portuguese Naval Academy for careers in maritime industry.'),
('University of Turin','Viticultural and Oenological Sciences','Italy','Torino',2.0,156,ARRAY['Agriculture','Viticulture','Food Science'],false,'MSc training highly qualified professionals with the skills for specialised tasks in viticulture and oenology sciences at an advanced level.'),
('Polytechnic Institute of Bragança','Management of Forest Resources','Portugal','Bragança',2.0,1441,ARRAY['Forestry','Natural Resource Management','Sustainability'],false,'MSc in forest resource management within Agriculture Sciences and Natural Resources, training graduates for professional activity in forest management.'),
('University of Debrecen','Plant Protection','Hungary','Debrecen',2.0,6888,ARRAY['Agriculture','Plant Science','Pest Management'],false,'MSc training plant protection specialists for directional, managing, and consulting tasks in crop production based on wide theoretical and practical knowledge.'),
('Slovak University of Agriculture in Nitra','Sustainability in Agriculture, Food Production and Food Technology in the Danube Region','Slovakia','Nitra',2.0,1500,ARRAY['Agriculture','Food Science','Sustainability'],false,'MSc applying knowledge to sustainably address microbiological contamination and food safety challenges in agriculture and food production.'),
('Czech University of Life Sciences Prague','European Agrarian Diplomacy','Czech Republic','Prague',2.0,515,ARRAY['Agriculture','EU Policy','Diplomacy'],false,'MSc educating specialists in EU Common Agricultural Policy for positions in national and European institutions; created at the request of the Czech Ministry of Agriculture.'),
('Swedish University of Agricultural Sciences','Euroforester','Sweden','Lomma',2.0,NULL,ARRAY['Forestry','Environmental Science','European Studies'],false,'MSc providing profound understanding in forest management, ecology, planning, and policy across different national traditions; tuition-free for EU students.'),
('Czech University of Life Sciences Prague','Tropical Crop Management and Ecology','Czech Republic','Prague',2.0,329,ARRAY['Agriculture','Tropical Agriculture','Ecology'],false,'Two-year MSc on crop production systems, ecology, and management practices in tropical and subtropical developing regions.'),
('University of Bordeaux','Biology Agrosciences','France','Bordeaux',1.0,254,ARRAY['Agriculture','Biology','Environmental Science'],false,'MSc based on an integrated multidisciplinary approach combining background research and professional courses in agrosciences and biology.'),
('University of Padua','Sustainable Agriculture','Italy','Legnaro',2.0,2739,ARRAY['Agriculture','Sustainability','Plant Science'],false,'MSc providing advanced knowledge of sustainable agricultural systems and skills to develop production systems in warm-temperate global environments.'),
('Szent István University','Food Science and Technology Engineering','Hungary','Budapest',2.0,6000,ARRAY['Food Science','Engineering','Technology'],false,'MSc training food engineers with the latest scientific knowledge in food science, natural sciences, and technical disciplines.'),
('MATE Hungarian University of Agriculture and Life Sciences','Animal Nutrition and Feed Safety Engineering','Hungary','Kaposvár',2.0,5000,ARRAY['Animal Science','Nutrition','Food Safety'],false,'MSc preparing professionals in animal production fields through advanced study in animal nutrition and feed safety engineering.'),
('University of Algarve','Food Technology','Portugal','Faro',2.0,1100,ARRAY['Food Science','Technology','Sustainability'],false,'MSc providing knowledge of food properties and production technologies to analyse, control, design, and innovate in food production systems.'),
('MATE Hungarian University of Agriculture and Life Sciences','Animal Husbandry Engineering','Hungary','Gödöllő',2.0,6000,ARRAY['Animal Science','Engineering','Agriculture'],false,'MSc training animal husbandry engineers with knowledge of animal science, agricultural technology, and economics for the livestock sector.'),
('Poznan University of Life Sciences','Forestry','Poland','Poznan',2.0,2100,ARRAY['Forestry','Environmental Science','Natural Resource Management'],false,'MSc for people pursuing careers in forestry, forest industry, environmental management, and nature protection areas.'),
('Technical University of Denmark','Sustainable Fisheries and Aquaculture (Hirtshals Campus)','Denmark','Hirtshals',2.0,NULL,ARRAY['Marine Science','Fisheries','Aquaculture'],false,'MSc equipping students with skills for sustainable development of capture fisheries and aquaculture production while assessing environmental change impacts; tuition-free for EU students.'),
('University of Hohenheim','Agricultural Sciences in the Tropics and Subtropics','Germany','Stuttgart',2.0,NULL,ARRAY['Agriculture','Tropical Agriculture','International Development'],false,'MSc available as a single degree at Hohenheim or double degree with Czech University of Life Sciences Prague in Tropical Agriculture and Farming Systems; tuition-free.'),
('University of Göttingen','Forest and Ecosystem Sciences - Tropical and International Forestry','Germany','Göttingen',2.0,NULL,ARRAY['Forestry','Tropical Ecology','International Studies'],false,'MSc tackling global change, climate warming, land use change, and biodiversity threats through hands-on approaches to international forest science; tuition-free.'),
('University of Copenhagen','Forest and Nature Management','Denmark','Copenhagen',2.0,NULL,ARRAY['Forestry','Ecology','Natural Resource Management'],false,'MSc on sustainable use and management of forest and nature areas, combining ecology, economics, quantitative modelling, and social science; tuition-free for EU students.'),
('University of Hohenheim','Crop Sciences','Germany','Stuttgart',2.0,NULL,ARRAY['Agriculture','Plant Science','Biotechnology'],false,'MSc training students for scientific tasks in research and the private sector with a strong methodological and biotechnological education in crop science; tuition-free.'),

-- ── PAGE 15 ────────────────────────────────────────────────────────────────
('University of the Basque Country','Renewable Energy in the Marine Environment (REM)','Spain','Bilbao',2.0,9000,ARRAY['Marine Science','Renewable Energy','Engineering'],false,'Erasmus Mundus MSc training specialists to achieve marine renewable energy challenges, responding to industry demand for skilled professionals.'),
('Universidade Nova de Lisboa','Food Technology and Safety','Portugal','Lisbon',2.0,1500,ARRAY['Food Science','Food Safety','Technology'],false,'MSc preparing professionals in food quality, production processes, and safety control for agro-food industries.'),
('Czech University of Life Sciences Prague','Wildlife and Livestock Production, Management and Conservation','Czech Republic','Prague',2.0,329,ARRAY['Wildlife Management','Animal Science','Conservation'],false,'MSc providing theoretical background in wild and domestic animal production, management, and conservation in tropical and developing regions.'),
('University of Zurich','Biology - Animal Behaviour','Switzerland','Zürich',1.5,1576,ARRAY['Animal Science','Biology','Behaviour'],false,'MSc providing understanding of the diversity, regulation, and function of animal and human behaviour from a biological and evolutionary perspective.'),
('University of Kiel','AgriGenomics','Germany','Kiel',2.0,NULL,ARRAY['Agriculture','Genomics','Biotechnology'],false,'MSc on application of genomics in agriculture to improve productivity and sustainability in crop and livestock production; tuition-free.'),
('Lund University','Food Technology and Nutrition','Sweden','Lund',2.0,NULL,ARRAY['Food Science','Nutrition','Technology'],false,'MSc for students wanting to work with innovative future foods addressing major health issues such as malnutrition and obesity; tuition-free for EU students.'),
('Lund University','Biology, Animal Ecology','Sweden','Lund',2.0,NULL,ARRAY['Animal Science','Biology','Ecology'],false,'MSc on evolutionary processes at the level of genes, individuals, and populations in animal ecology; tuition-free for EU students.'),
('UniLaSalle','Urban Agriculture and Green Cities','France','Rouen',1.5,6400,ARRAY['Agriculture','Urban Studies','Sustainability'],false,'Cross-disciplinary MSc training future managers who see urban agriculture as an integral component of the entire urban life cycle.'),
('Swedish University of Agricultural Sciences','Horticultural Science','Sweden','Lomma',2.0,NULL,ARRAY['Agriculture','Horticulture','Sustainability'],false,'MSc offering a holistic view of sustainable horticultural cultivation systems for careers in production management and crop development; tuition-free for EU students.'),
('Lund University','Food Innovation and Product Design','Sweden','Lund',2.0,4500,ARRAY['Food Science','Innovation','Product Design'],true,'Erasmus Mundus joint MSc in food science and product development operated with AgroParisTech, TU Dublin, UNINA, and Paris-Saclay; scholarship available.'),
('Swedish University of Agricultural Sciences','Forest Ecology and Sustainable Management','Sweden','Lomma',2.0,NULL,ARRAY['Forestry','Ecology','Sustainability'],false,'MSc for students aiming for professional or academic careers in applied forest ecology, silviculture, and forest resource management; tuition-free for EU students.'),
('University College Dublin','Food Engineering','Ireland','Dublin',1.0,9720,ARRAY['Food Science','Engineering','Biotechnology'],false,'MSc focused on bioprocess and food manufacturing systems, equipping graduates with technical expertise in risk assessment and process automation for agri-food sectors.'),
('Ghent University','Marine and Lacustrine Science and Management (Ghent)','Belgium','Gent',2.0,1157,ARRAY['Marine Science','Freshwater Science','Management'],false,'MSc providing strong fundamental and applied knowledge in marine and lacustrine systems, preparing students for scientific research and management roles.'),
('JUNIA - Graduate School of Science and Engineering','Smart Farming and Sustainable Agriculture','France','Lille',2.0,9770,ARRAY['Agriculture','Precision Farming','Sustainability'],false,'MSc deepening understanding of sustainable agrifood chains through plant biotechnologies, biocontrol, precision livestock farming, and climate-aware farming solutions.'),
('University of Gothenburg','Marine Biological Resources','Sweden','Göteborg',2.0,3000,ARRAY['Marine Science','Biology','Resource Management'],true,'Erasmus Mundus joint MSc in Marine Biological Resources (IMBRSea) with emphasis on marine biological and ecological processes; scholarship available.'),

-- ── PAGE 16 ────────────────────────────────────────────────────────────────
('University of Natural Resources and Life Sciences Vienna','Sustainability in Agriculture, Food Production and Food Technology','Austria','Vienna',2.0,726,ARRAY['Agriculture','Food Science','Sustainability'],false,'MSc improving knowledge of intercultural and sustainability aspects in agriculture and the food industry across the Danube region countries.'),
('Dundalk Institute of Technology','Sustainable Food Technology and Innovation','Ireland','Dundalk',1.0,7650,ARRAY['Food Science','Technology','Sustainability'],false,'New MSc in sustainable food technology and innovation delivered by blended mode covering emerging technologies for sustainable food production.'),
('Audencia','MSc in Food and Agribusiness Management','France','Nantes',1.0,17057,ARRAY['Agriculture','Food Science','Business Management'],false,'MSc covering the major disciplines of management science applied to the agribusiness sector, preparing leaders for global food and agri industries.'),
('Ghent University','AquaH - International Master of Science in Health Management in Aquaculture','Belgium','Gent',2.0,4500,ARRAY['Aquaculture','Marine Science','Animal Health'],false,'MSc contributing to sustainable seafood supply by training experts to develop innovative solutions to current and future health challenges in the aquaculture industry.')

) AS v(university, program_name, country, city, duration_years, tuition_eur, fields, scholarship, description)
ON CONFLICT (fingerprint) DO NOTHING;
