-- ============================================================
-- Seed: Agriculture & Forestry Master's programs from Mastersportal
-- Source: mastersportal.eu — pages 6–10 (~95 programs)
-- Run AFTER seed_masters.sql AND migrate_programs.sql
-- Safe to run multiple times — ON CONFLICT (fingerprint) DO NOTHING
-- ============================================================

INSERT INTO masters_programs (
  university, program_name, country, city, category,
  duration_years, tuition_usd_year, language,
  field_of_study, scholarship_available, description,
  level, source_name, source_url, apply_url, fingerprint
)
SELECT
  v.university, v.program_name, v.country, v.city, 'agriculture',
  v.duration_years, v.tuition_eur, 'English',
  v.fields, v.scholarship, v.description,
  'master', 'mastersportal',
  'https://www.mastersportal.eu/disciplines/0/agriculture-forestry.html', '',
  encode(sha256((lower(trim(v.program_name)) || '|' || lower(v.country) || '|master')::bytea), 'hex')
FROM (VALUES

-- ── PAGE 6 ─────────────────────────────────────────────────────────────────
('University of Galway','Climate Change, Agriculture and Food Security','Ireland','Galway',1.0,8750,ARRAY['Agriculture','Climate Science','Food Security'],false,'MSc addressing the impacts of climate change on agriculture and global food systems, combining research and fieldwork.'),
('University of Natural Resources and Life Sciences Vienna','Plant Breeding','Austria','Vienna',2.0,726,ARRAY['Agriculture','Plant Science','Biotechnology'],true,'Erasmus Mundus joint master in plant breeding with a focus on genetic improvement for sustainable agriculture.'),
('University of Natural Resources and Life Sciences Vienna','Limnology and Wetland Management','Austria','Vienna',2.0,726,ARRAY['Environmental Science','Freshwater Science','Ecology'],false,'MSc on freshwater ecosystems, wetland conservation, and sustainable water resource management in Europe.'),
('World Maritime University','Maritime Affairs','Sweden','Malmö',1.0,21771,ARRAY['Marine Science','Maritime','Management'],false,'International programme for maritime professionals focusing on leadership, policy, and ocean governance.'),
('Czech University of Life Sciences Prague','Erasmus Mundus Danube Agrifood','Czech Republic','Prague',2.0,NULL,ARRAY['Agriculture','Food Science','Sustainability'],true,'Erasmus Mundus joint programme on agrifood systems and rural development in the Danube region; full scholarship available.'),
('University of Algarve','Marine, Biodiversity, Fisheries and Conservation','Portugal','Faro',2.0,1100,ARRAY['Marine Science','Fisheries','Conservation'],false,'MSc exploring marine biodiversity, fisheries management, and conservation strategies in Atlantic and Mediterranean systems.'),
('Polytechnic University of Catalonia','Coastal and Marine Engineering and Management','Spain','Barcelona',2.0,NULL,ARRAY['Marine Science','Engineering','Coastal Management'],false,'Joint programme on coastal engineering, marine environment, and integrated coastal zone management; tuition-free.'),
('Polytechnic University of Valencia','Plant Health in Sustainable Cropping Systems','Spain','Valencia',2.0,2340,ARRAY['Agriculture','Plant Science','Sustainability'],true,'Erasmus Mundus programme on integrated pest management and plant health in sustainable agricultural systems.'),
('Bern University of Applied Sciences','Life Sciences - Agricultural Science','Switzerland','Bern',1.5,2079,ARRAY['Agriculture','Life Sciences','Sustainability'],false,'Applied sciences programme covering crop production, animal husbandry, and sustainable land management.'),
('Universidade Nova de Lisboa','Marine Living Resources','Portugal','Lisbon',1.5,1250,ARRAY['Marine Science','Biology','Resource Management'],false,'MSc focusing on the sustainable exploitation and conservation of marine living resources.'),
('University of Lleida','Mediterranean Forestry and Natural Resources Management','Spain','Lleida',2.0,3000,ARRAY['Forestry','Natural Resource Management','Mediterranean Ecology'],false,'MSc on forest and natural resource management adapted to Mediterranean climate conditions and ecosystems.'),
('University of Padua','Italian Food and Wine','Italy','Legnaro',2.0,2739,ARRAY['Food Science','Agriculture','Gastronomy'],false,'Interdisciplinary programme on Italian food culture, wine production, and agro-food value chains.'),
('Bern University of Applied Sciences','Wood Technology','Switzerland','Bern',2.0,2079,ARRAY['Forestry','Wood Science','Engineering'],false,'MSc in wood technology covering material properties, processing, and sustainable use of wood in construction and industry.'),
('MATE Hungarian University of Agriculture and Life Sciences','Agricultural Economist','Hungary','Budapest',2.0,6000,ARRAY['Agriculture','Economics','Rural Development'],false,'MSc in agricultural economics covering farm management, agri-food markets, and rural policy.'),
('MATE Hungarian University of Agriculture and Life Sciences','Aquaculture','Hungary','Budapest',2.0,6000,ARRAY['Aquaculture','Animal Science','Marine Science'],false,'MSc in aquaculture covering freshwater and marine fish production, water quality, and aquatic health management.'),
('Czech University of Life Sciences Prague','Forestry, Water and Landscape Management','Czech Republic','Prague',2.0,3706,ARRAY['Forestry','Water Management','Landscape Ecology'],false,'MSc integrating forestry, watershed management, and landscape planning in Central European ecosystems.'),
('Aarhus University','Agrobiology','Denmark','Aarhus',2.0,NULL,ARRAY['Agriculture','Biology','Sustainability'],false,'Research-based MSc in plant and animal science, agro-ecology, and sustainable food production systems; tuition-free for EU students.'),

-- ── PAGE 7 ─────────────────────────────────────────────────────────────────
('Norwegian University of Science and Technology','Marine Technology','Norway','Trondheim',2.0,NULL,ARRAY['Marine Science','Engineering','Technology'],false,'MSc covering marine structures, hydrodynamics, offshore engineering, and ocean operations; tuition-free.'),
('University of Padua','Plant Health in Sustainable Cropping Systems','Italy','Padova',2.0,4500,ARRAY['Agriculture','Plant Science','Sustainability'],false,'MSc on integrated crop protection, phytopathology, and sustainable farming systems.'),
('Nord University','Sustainable Production and Utilization of Marine Bioresources','Norway','Bodø',2.0,16779,ARRAY['Marine Science','Sustainability','Bioresources'],false,'MSc on sustainable use of marine biological resources, covering fisheries, aquaculture, and marine biotechnology.'),
('University of Salento','Coastal and Marine Biology and Ecology','Italy','Lecce',2.0,NULL,ARRAY['Marine Science','Biology','Ecology'],false,'MSc on marine biodiversity, coastal ecosystems, and applied biological research in Mediterranean environments.'),
('Warsaw University of Life Sciences','Forest Information Technology','Poland','Warsaw',2.0,NULL,ARRAY['Forestry','Information Technology','Remote Sensing'],false,'MSc combining forestry sciences with GIS, remote sensing, and digital technologies for forest management; tuition-free for EU students.'),
('Lithuanian University of Health Sciences','Animal Science','Lithuania','Kaunas',2.0,5538,ARRAY['Animal Science','Veterinary Science','Sustainability'],false,'MSc in animal husbandry, production systems, and animal welfare with a focus on health and productivity.'),
('Centrale Nantes','Renewable Energy in the Marine Environment','France','Nantes',2.0,4500,ARRAY['Marine Science','Renewable Energy','Engineering'],true,'Erasmus Mundus programme on marine renewable energy technologies including offshore wind, tidal, and wave energy.'),
('ETH Zurich','Agricultural Sciences','Switzerland','Zurich',2.0,1598,ARRAY['Agriculture','Life Sciences','Sustainability'],false,'Research-oriented MSc covering plant science, animal physiology, food systems, and agro-ecosystem management.'),
('Szent István University','Horticultural Engineering','Hungary','Budapest',2.0,6000,ARRAY['Agriculture','Horticulture','Engineering'],false,'MSc in horticulture covering vegetable, fruit, and ornamental plant production for sustainable food systems.'),
('University of Algarve','Marine and Coastal Systems','Portugal','Faro',2.0,1100,ARRAY['Marine Science','Coastal Management','Environmental Science'],false,'MSc focused on marine and coastal ecosystem research, conservation, and integrated management strategies.'),
('Mendel University in Brno','General Agriculture','Czech Republic','Brno',2.0,3295,ARRAY['Agriculture','Agronomy','Sustainability'],false,'Comprehensive MSc in crop production, soil management, and sustainable agricultural practices.'),
('Slovak University of Technology','Automation and Information Engineering in Chemistry and Food Industry','Slovakia','Bratislava',2.0,3500,ARRAY['Food Science','Engineering','Automation'],false,'MSc at the intersection of food industry automation, process control, and information technology.'),
('Bordeaux Sciences Agro','Vineyard and Winery Management','France','Bordeaux',2.0,11000,ARRAY['Agriculture','Viticulture','Management'],false,'International MSc in vineyard management, wine production, and business strategy for the global wine industry.'),
('University of Eastern Finland','Forestry','Finland','Joensuu',2.0,NULL,ARRAY['Forestry','Environmental Science','Sustainability'],false,'MSc in forest sciences, ecosystem management, and climate-smart forestry; tuition-free for EU students.'),
('University of Copenhagen','Food Science and Technology','Denmark','Copenhagen',2.0,NULL,ARRAY['Food Science','Technology','Sustainability'],false,'MSc on food product development, quality control, and food systems innovation; tuition-free for EU students.'),
('University of Copenhagen','Animal Science','Denmark','Copenhagen',2.0,NULL,ARRAY['Animal Science','Sustainability','Biology'],false,'Research-focused MSc in animal production, animal behaviour, and sustainable livestock systems; tuition-free for EU students.'),
('University of Eastern Finland','European Forestry','Finland','Joensuu',2.0,NULL,ARRAY['Forestry','European Studies','Sustainability'],true,'Erasmus Mundus joint programme in European forestry with mobility across multiple European universities; full scholarship available.'),
('University of Hohenheim','Organic Agriculture and Food Systems','Germany','Stuttgart',2.0,NULL,ARRAY['Agriculture','Organic Farming','Food Systems'],false,'MSc focusing on organic farming principles, food chain sustainability, and rural development; tuition-free.'),
('University of Bonn','Agricultural Sciences and Resource Management in the Tropics and Subtropics','Germany','Bonn',2.0,NULL,ARRAY['Agriculture','Tropical Agriculture','Resource Management'],false,'MSc addressing food security, sustainable land use, and development in tropical and subtropical regions; tuition-free.'),

-- ── PAGE 8 ─────────────────────────────────────────────────────────────────
('University of Bordeaux','Wine Tourism Innovation','France','Bordeaux',2.0,6000,ARRAY['Agriculture','Wine Tourism','Innovation'],false,'MSc at the crossroads of wine culture, sustainable tourism, and rural innovation in wine-producing regions.'),
('TU Dresden','Tropical Forestry','Germany','Dresden',2.0,NULL,ARRAY['Forestry','Tropical Ecology','Sustainability'],false,'MSc in tropical and subtropical forest management, conservation biology, and international forest policy; tuition-free.'),
('Technical University of Munich','Agricultural Biosciences','Germany','Munich',2.0,NULL,ARRAY['Agriculture','Biosciences','Biotechnology'],false,'Research-oriented MSc combining plant science, animal science, and biotechnology for sustainable agriculture; tuition-free.'),
('University of Hamburg','Marine Ecosystem and Fisheries Science','Germany','Hamburg',2.0,NULL,ARRAY['Marine Science','Fisheries','Ecology'],false,'MSc on marine ecosystems, fish stock dynamics, and sustainable fisheries management in a changing ocean; tuition-free.'),
('University of Bonn','Agricultural and Food Economics','Germany','Bonn',2.0,NULL,ARRAY['Agriculture','Economics','Food Systems'],false,'MSc integrating agricultural economics, market analysis, and food policy for sustainable development; tuition-free.'),
('University of Göttingen','Forest and Ecosystem Sciences','Germany','Göttingen',2.0,NULL,ARRAY['Forestry','Ecology','Environmental Science'],false,'MSc on forest ecology, biodiversity, and ecosystem services within the context of global environmental change; tuition-free.'),
('University of Freiburg','Forest Sciences','Germany','Freiburg',2.0,NULL,ARRAY['Forestry','Sustainability','Environmental Science'],false,'International MSc providing expertise in forest ecosystem management, climate adaptation, and forest policy; tuition-free.'),
('University of Antwerp','Marine and Lacustrine Science and Management','Belgium','Antwerp',2.0,1181,ARRAY['Marine Science','Freshwater Science','Management'],false,'MSc on the ecology, chemistry, and management of marine and freshwater ecosystems in the Antwerp region and beyond.'),
('University of Kiel','Dairy Science','Germany','Kiel',2.0,NULL,ARRAY['Animal Science','Food Science','Agriculture'],false,'Specialised MSc on dairy cattle production, milk processing, and quality assurance in the dairy sector; tuition-free.'),
('University of Galway','Marine and Freshwater Resources Management','Ireland','Galway',1.0,8890,ARRAY['Marine Science','Freshwater Science','Resource Management'],false,'MSc on the sustainable management of marine and freshwater resources integrating ecology, law, and policy.'),
('Agro Rennes-Angers Institute','Plant Health in Sustainable Cropping Systems','France','Rennes',2.0,4500,ARRAY['Agriculture','Plant Science','Sustainability'],false,'MSc part of the Erasmus Mundus PLANT-HEALTH network on integrated pest management and sustainable crop protection.'),
('University College Dublin','Sustainable Agriculture and Rural Development','Ireland','Dublin',1.0,10430,ARRAY['Agriculture','Rural Development','Sustainability'],false,'MSc addressing the societal and environmental challenges of transitioning to sustainable food and farming systems.'),
('AgroParisTech','Forest, Nature and Society - International Management','France','Paris',1.0,10000,ARRAY['Forestry','Natural Resource Management','International Studies'],false,'MSc preparing future decision-makers for international forest and nature management at the science-policy interface.'),
('Norwegian University of Science and Technology','Ocean Resources','Norway','Trondheim',2.0,NULL,ARRAY['Marine Science','Resource Management','Sustainability'],false,'MSc on sustainable management and exploitation of ocean biological and mineral resources; tuition-free.'),
('Norwegian University of Life Sciences','Plant Sciences','Norway','Ås',2.0,NULL,ARRAY['Agriculture','Plant Science','Biology'],false,'MSc in plant biology, crop improvement, and sustainable plant production systems in temperate climates; tuition-free.'),
('Norwegian University of Life Sciences','Aquatic Food Production - Safety and Quality','Norway','Ås',2.0,NULL,ARRAY['Aquaculture','Food Science','Marine Science'],false,'MSc on the safety, quality, and sustainability of food production from aquatic organisms; tuition-free.'),
('University of Algarve','Marine Biological Resources','Portugal','Faro',2.0,4500,ARRAY['Marine Science','Biology','Resource Management'],true,'Erasmus Mundus joint MSc on the ecology and sustainable management of marine biological resources across European seas.'),
('University of Iceland','Aquatic Biology and Fisheries','Iceland','Reykjavik',2.0,NULL,ARRAY['Marine Science','Biology','Fisheries'],false,'MSc on aquatic ecology, fish biology, and fisheries science adapted to sub-arctic and North Atlantic environments; tuition-free.'),
('Agro Rennes-Angers Institute','Agrosciences, Environment, Territories, Landscape and Forest','France','Rennes',2.0,4500,ARRAY['Agriculture','Environmental Science','Forestry'],false,'MSc integrating agronomy, ecology, landscape management, and forest sciences for sustainable territorial development.'),

-- ── PAGE 9 ─────────────────────────────────────────────────────────────────
('Norwegian University of Life Sciences','Animal Science','Norway','Ås',2.0,NULL,ARRAY['Animal Science','Biology','Sustainability'],false,'MSc covering livestock production, animal nutrition, breeding, and welfare in sustainable food systems; tuition-free.'),
('Free University of Bozen-Bolzano','Horticultural Science','Italy','Bolzano',2.0,NULL,ARRAY['Agriculture','Horticulture','Plant Science'],false,'MSc in fruit and vegetable production, protected cropping, and sustainable horticultural systems in alpine environments.'),
('Norwegian University of Science and Technology','Coastal and Marine Engineering and Management','Norway','Trondheim',2.0,NULL,ARRAY['Marine Science','Engineering','Coastal Management'],false,'MSc on coastal engineering, marine operations, and integrated management of coastal and offshore environments; tuition-free.'),
('University of Warmia and Mazury','Food Engineering','Poland','Olsztyn',1.5,NULL,ARRAY['Food Science','Engineering','Technology'],false,'MSc in food processing technology, engineering design, and quality management in the food industry; tuition-free for EU students.'),
('Università degli Studi della Tuscia','Forestry and Environmental Sciences','Italy','Viterbo',3.0,1000,ARRAY['Forestry','Environmental Science','Ecology'],false,'Three-year MSc on forest ecology, biodiversity conservation, and sustainable land management in Mediterranean and mountain ecosystems.'),
('University of Padua','Global Forestry','Italy','Padova',2.0,NULL,ARRAY['Forestry','Sustainability','Global Studies'],true,'Erasmus Mundus joint MSc on global forest governance, ecosystem services, and sustainable forest management; full scholarship available.'),
('Czech University of Life Sciences Prague','Forest Science in Global Change','Czech Republic','Prague',2.0,3706,ARRAY['Forestry','Environmental Science','Climate Change'],false,'MSc addressing the impacts of global environmental change on forest ecosystems and sustainable management responses.'),
('Czech University of Life Sciences Prague','Agricultural Engineering','Czech Republic','Prague',2.0,13000,ARRAY['Agriculture','Engineering','Technology'],false,'MSc in advanced agricultural machinery, precision farming, and smart agricultural technology solutions.'),
('University of Naples Federico II','Precision Livestock Farming','Italy','Naples',2.0,200,ARRAY['Animal Science','Technology','Precision Farming'],false,'MSc on digital technologies, sensors, and data-driven management for precision monitoring of livestock systems.'),
('University of Life Sciences in Lublin','Agriculture','Poland','Lublin',1.5,2400,ARRAY['Agriculture','Agronomy','Sustainability'],false,'MSc in crop production, soil fertility, and sustainable land use in continental European agricultural systems.'),
('University of Turin','Animal Nutrition and Feed Safety','Italy','Turin',2.0,156,ARRAY['Animal Science','Food Science','Nutrition'],false,'MSc on animal feed formulation, nutritional requirements, and safety standards in sustainable livestock systems.'),
('MATE Hungarian University of Agriculture and Life Sciences','Viticulture and Oenology Engineering','Hungary','Budapest',2.0,6000,ARRAY['Agriculture','Viticulture','Food Science'],false,'MSc in viticulture, winemaking technology, and enological engineering for the global wine industry.'),
('Czech University of Life Sciences Prague','Sustainable Agriculture and Food Security','Czech Republic','Prague',2.0,515,ARRAY['Agriculture','Food Security','Sustainability'],false,'MSc on sustainable farming systems and food policy in the context of global food security challenges.'),
('Czech University of Life Sciences Prague','International Development and Agricultural Economics','Czech Republic','Prague',2.0,329,ARRAY['Agriculture','Economics','International Development'],false,'MSc linking agricultural economics with development studies for careers in international organisations and NGOs.'),
('University of Bologna','International Horticultural Science','Italy','Bologna',2.0,157,ARRAY['Agriculture','Horticulture','International Studies'],false,'MSc on sustainable horticulture combining plant science, food quality, and international agricultural trade.'),
('Norwegian University of Life Sciences','Aquaculture','Norway','Ås',2.0,NULL,ARRAY['Aquaculture','Marine Science','Biology'],false,'MSc covering fish physiology, aquaculture production systems, disease management, and environmental impacts; tuition-free.'),
('University of Malta','Applied Oceanography','Malta','Valletta',1.5,NULL,ARRAY['Marine Science','Oceanography','Environmental Science'],false,'MSc in physical, chemical, and biological oceanography with applications to ocean monitoring and resource management; tuition-free.'),
('University of Sassari','Animal Production Sciences','Italy','Sassari',2.0,NULL,ARRAY['Animal Science','Agriculture','Sustainability'],false,'MSc on livestock production, breeding, and management with a focus on Mediterranean animal production systems.'),
('Czech University of Life Sciences Prague','Tropical Forestry and Agroforestry','Czech Republic','Prague',2.0,329,ARRAY['Forestry','Tropical Agriculture','Sustainability'],false,'MSc on forest management and agroforestry systems in tropical and subtropical regions for sustainable development.'),
('Czech University of Life Sciences Prague','Agri-food Systems and Rural Development','Czech Republic','Prague',2.0,329,ARRAY['Agriculture','Food Systems','Rural Development'],false,'MSc on agri-food chain governance, rural development policies, and sustainable territorial strategies.'),

-- ── PAGE 10 ────────────────────────────────────────────────────────────────
('Czech University of Life Sciences Prague','Tropical Farming Systems','Czech Republic','Prague',2.0,535,ARRAY['Agriculture','Tropical Agriculture','Sustainability'],false,'MSc on smallholder farming, land management, and food systems in tropical developing countries.'),
('EU-CONEXUS European University','Joint Master Programme in Marine Biotechnology','Romania','Constanta',2.0,5000,ARRAY['Marine Science','Biotechnology','Life Sciences'],false,'International joint MSc on marine biotechnology, blue bioeconomy, and innovative applications of marine organisms.'),
('Transilvania University of Brasov','Multiple Purpose Forestry','Romania','Brasov',2.0,764,ARRAY['Forestry','Natural Resource Management','Sustainability'],false,'MSc on multifunctional forest management balancing wood production, biodiversity, and ecosystem services.'),
('Institut Agro Montpellier','Vinifera EuroMaster','France','Montpellier',2.0,9000,ARRAY['Agriculture','Viticulture','Wine Science'],false,'Joint European MSc in viticulture and oenology with mobility across leading wine regions in France, Italy, and Germany.'),
('University of Göttingen','Crop Protection','Germany','Göttingen',2.0,NULL,ARRAY['Agriculture','Plant Science','Pest Management'],false,'MSc on crop diseases, pests, integrated protection strategies, and pesticide science in sustainable agriculture; tuition-free.'),
('University of Copenhagen','Sustainable Forest and Nature Management','Denmark','Copenhagen',2.0,NULL,ARRAY['Forestry','Ecology','Sustainability'],false,'Erasmus Mundus-linked joint MSc on sustainable forest management and nature conservation across Europe; tuition-free for EU students.'),
('Linköping University','Applied Ethology and Animal Biology','Sweden','Linköping',2.0,NULL,ARRAY['Animal Science','Biology','Ethology'],false,'MSc on animal behaviour, welfare science, and applied ethology for livestock, companion animals, and wildlife; tuition-free for EU students.'),
('Justus Liebig University Giessen','Agrobiotechnology','Germany','Giessen',2.0,NULL,ARRAY['Agriculture','Biotechnology','Life Sciences'],false,'MSc combining plant and animal biotechnology with agricultural applications for sustainable production systems; tuition-free.'),
('Swedish University of Agricultural Sciences','Agricultural, Food and Environmental Policy Analysis','Sweden','Uppsala',2.0,NULL,ARRAY['Agriculture','Food Policy','Environmental Science'],false,'MSc on the design, analysis, and evaluation of policies governing agriculture, food, and natural resources; tuition-free for EU students.'),
('Swedish University of Agricultural Sciences','Agroecology','Sweden','Uppsala',2.0,NULL,ARRAY['Agriculture','Ecology','Sustainability'],false,'MSc on ecological principles in agricultural system design, biodiversity-based farming, and sustainable food production; tuition-free for EU students.'),
('Latvia University of Life Sciences and Technologies','Agricultural Engineering','Latvia','Jelgava',2.0,3000,ARRAY['Agriculture','Engineering','Technology'],false,'MSc in agricultural machinery, precision farming technologies, and mechanisation of crop and livestock production.'),
('University College Dublin','Biosystems and Food Engineering','Ireland','Dublin',2.0,9530,ARRAY['Food Science','Engineering','Biotechnology'],false,'MSc on bioprocess engineering, food technology, and sustainable systems for the agri-food and bioeconomy sectors.'),
('Paris-Saclay University','Predictive and Integrative Animal Biology','France','Paris',1.0,250,ARRAY['Animal Science','Biology','Data Science'],false,'MSc using data science and modelling approaches to understand and predict animal physiology and behaviour.'),
('University of Lorraine','Forestry','France','Nancy',2.0,4250,ARRAY['Forestry','Environmental Science','Sustainability'],false,'MSc in forest ecosystem science, wood production, and integrated forest management across European forest types.'),
('University of Hamburg','Wood Science','Germany','Hamburg',2.0,NULL,ARRAY['Forestry','Wood Science','Engineering'],false,'MSc on wood as a material — biology, properties, processing, and sustainable use in construction and industry; tuition-free.'),
('ISARA','Agroecology - Resilient Farming','France','Lyon',2.0,5500,ARRAY['Agriculture','Agroecology','Sustainability'],false,'MSc designing resilient farming systems based on agroecological principles for a changing climate.'),
('University College Dublin','Digital Technology for Sustainable Agriculture','Ireland','Dublin',1.0,9530,ARRAY['Agriculture','Digital Technology','Sustainability'],false,'MSc on precision agriculture, IoT sensors, data analytics, and digital tools for sustainable farm management.'),
('Linnaeus University','Forestry for Green Sustainable Development','Sweden','Växjö',2.0,NULL,ARRAY['Forestry','Sustainability','Green Economy'],false,'MSc on sustainable forestry, biomass production, and the role of forests in the green bioeconomy; tuition-free for EU students.')

) AS v(university, program_name, country, city, duration_years, tuition_eur, fields, scholarship, description)
ON CONFLICT (fingerprint) DO NOTHING;
